### ISSUE TITLE
Hotkey used can not be reassigned

### ISSUE THREAD

**Issue by jsu1337** [terrymacdonald/DisplayMagician#102]
- Windows Version: 10 pro
 - DisplayMagician Version 2.3.1
 - Video Card: Asus NVIDIA RTX 3080
 - Number and make/model of monitors: 3xLG 32GN650, 1x LG 27GP750
 - Date of last video driver update: 512.15
 - Date of last windows update: 2022-05-03

I have two profile and each assigned hot key "ctrl+alt+shift+1" and "ctrl+alt+shift+2"
then I changed to something else, now I want previous hot key back but can not set "ctrl+alt+shift+1" or "ctrl+alt+shift+2" again

**Comment by terrymacdonald** [comment]
@jsu1337 If you still have the Display Profiles that contain the Hotkeys, then you can click on the Hotkey button in that Display Profile or Game Shortcut, and you can click the Clear button to remove the hotkey. 

If that is not possible (say you have deleted the hotkey), then you can instead clear all the hotkeys and then add them again. You should be able to press the **Clear All Hotkeys** button in the **Settings** window, which you can get to via the Settings button on the Main DisplayMagician page. That should clear all the hot keys that are related to Display Profiles or Game Shortcuts.

Hopefully that works ok? Please reply here and tell me if it works or not, and then we'll continue troubleshooting if needed.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@jsu1337 I also tested myself just now, and if you delete a Display Profile or Shortcut that contains a HotKey, then unfortunately DisplayMagician won't let you reuse that HotKey again on a different Display Profile or Game Shortcut **until you restart DisplayMagician**.

So my advice is to exit DisplayMagician (don't just close it to the system tray, exit the application) and the restart DisplayMagician. You should be able to reuse your HotKeys from then on.

I will try to fix that in the main code base so the fix will be part of the next release of DisplayMagician.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@jsu1337 I just created a fix for the mainline codebase and tested it. It works, so I will close this issue.

The fix will come out in DisplayMagician v2.4.0 which will be a month or two away. v2.4.0 will also hopefully include support for Windows Store games as well (though that is proving more difficult than expected). 

Thanks
Terry

**Comment by jsu1337** [comment]
restart app will let me register used hotkey again. thank you!
