### ISSUE TITLE
Problem with additional program in game profile

### ISSUE THREAD

**Issue by Manfredk2** [terrymacdonald/DisplayMagician#112]
I created a game profile for Rfactor 2 and added some programs to start before Rfactor 2 launches

Works great but there is one program called Tinypedal https://github.com/s-victor/TinyPedal/releases which does not work. Tinypedal reads and writes a config file called config.json. And this is the problem because tinypedal probably does not "see" its own directory folder. Probably it lacks some kind of "start location" so tinypedal could not find his config.

Any help for solving this appreciated. My workaround is starting a program called tmautostart via Displaymagician which starts tinypedal

**Comment by terrymacdonald** [comment]
Hi @Manfredk2,

 I was about to tell you that there isn't anything I can do, as it is a python program, and would likely need to be called a different way, but then I realised that I probably aren't setting the working directory when the process is being passed it's ProcessStartInfo object. And a quick look confirmed this to be true. 

What this means is that I *should* be able to help in your particular case. There is still a chance that this wont work with tinypedal by just running the tinypedal.py, but that is then up to how you've installed python (and what version of python you're running). I will at least be able to set the working directory correctly.

I'll have to do some testing to make sure it doesn't break other parts of DisplayMagician that rely on the TryExecute function, and you'll see some code changes referenced here if it does work out.

Thanks
Terry

**Comment by Manfredk2** [comment]
great, thank you

**Comment by terrymacdonald** [comment]
The changes are now in the codebase and will be released when DisplayMagician v2.3.2 is released. For that reason I will close this issue so that I can keep track of what work I still have to do.

If you still have problems when v2.3.2 is released, then feel free to reopen this issue.
