### ISSUE TITLE
Primary monitor isn't being set

### ISSUE THREAD

**Issue by terrymacdonald** [terrymacdonald/DisplayMagician#119]
Hi,

Using v2.4.0.10 has fixed the issue where the 4th monitor used to turn off, so this is great news!

However when switching back to the profile where nvidia surround is off the centre display isn't set to the main display.  However windows display settings show it as the main strangely enough??

![Screenshot 2022-06-08 183917](https://user-images.githubusercontent.com/19865649/172682293-db18272c-e5c9-42ea-a3f1-699bc4f7f40b.png)

![Screenshot 2022-06-08 184210](https://user-images.githubusercontent.com/19865649/172682526-e4dd325b-06f4-4c8e-b9ee-495ec23b66b2.png)

I think this is a windows issue though and not sure if there is anything you can do to solve this with your software?  I fix this myself by setting "Display 1" to be the main display and then settings "Display 2" to be the main monitor again.  I did make sure "Display 2" was the main display when I created this profile in DisplayMagician.

Thanks,
Kevin

_Originally posted by @TOCA2FREAK in https://github.com/terrymacdonald/DisplayMagician/issues/116#issuecomment-1150212746_

**Comment by terrymacdonald** [comment]
@TOCA2FREAK, I've found a couple of things that seem to be the cause of the error you got. 

1. It looks like NVIDIA have made their NvAPI_Mosaic_SetDisplayGrids function only work with a SET_TOPOLOGY_FLAG value of NONE in the latest version of the driver. All other flag values results in a Crash to Desktop (CTD) :(. I have removed the other flags I used so that the driver will keep working.

2. Patch adapter ids (which patches Windows adapter ids so they work after a reboot) had a bug caused in a recent update. This would only update the first adapter seen, and not any others. This meant that a config wouldn't work after a reboot.

I have also updated the UI window placement when applying a profile. Because the screen coordinates change when applying a new display layout, the UI used to sometimes go off screen, and it was a pain to try and move it to the right place so you could see it again. I have changed that so that when a display profile is applied it will move the UI to the middle of the primary monitor, and will also then center the Display Profile screen. This should make DisplayMagician far easier to use.

To install DisplayMagician v2.4.0.26, please download this zip file and install the exe inside it. Please test the software and make sure that it now swaps display profiles without any errors: 
[DisplayMagicianSetup-v2.4.0.26.zip](https://github.com/terrymacdonald/DisplayMagician/files/8869771/DisplayMagicianSetup-v2.4.0.26.zip)

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
Awesome stuff!!

v2.4.0.26 has fixed all the issues I was having. :)

**Comment by TOCA2FREAK** [comment]
Actually.  I've just finished playing iRacing and when changing profile back to nvidia surround off I've got that same issue where the main monitor is on the left and not in the centre even though Windows shows the centre as the main. :(

**Comment by terrymacdonald** [comment]
When that happens next please close Windows Display Settings, and then reopen it. Windows Display Settings expects that it is the  only thing that can change the display layout, so doesn't update when DisplayMagician makes it's changes. You need to either go to another part of the Windows settings, or close it and reopen it for the Display layout to be updated in Windows Display Settings.

Try that, and see if the DisplayMagician and Windows Display Layouts end up being the same.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
It's happened again.  I closed windows display settings re-opened it and it still shows Display 2 as main display but it's actually Display 1 that is the main display.

FYI It is Display 2 that I want to be set to the main display as show in the screenshot in post #1

**Comment by terrymacdonald** [comment]
I have a theory. Can you please delete the existing display profiles you
have, and then create new ones, but please wait 30 seconds after changing
the display layout before you save it in DisplayMagician.

I have a gut feeling that it may be related to the delay that windows does
with taskbar layout. Windows only updated registry keys after 20 seconds or
so. Buy waiting 30 seconds after making a change before saving the display
profile, we can be sure the display profile is correct.

Can you try that for me please?

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
Okay I did as you suggested above, but still the same issue occurs. :(

**Comment by terrymacdonald** [comment]
Ok, can you please create a Support ZIP file and upload it here please. It
will hopefully have some errors in the logs that will help me figure out
what's going on.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
[DisplayMagician-Support-20220611-1352.zip](https://github.com/terrymacdonald/DisplayMagician/files/8883897/DisplayMagician-Support-20220611-1352.zip)

**Comment by terrymacdonald** [comment]
@TOCA2FREAK OK - so I've now updated the WinLibrary to attempt to force set the primary display. It is possible that the Windows CCD API isn't setting the primary display properly, so I'm instead trying to use the Windows GDI API to be able to do it.

I really need to isolate the errors to just the WinLibrary, so I'm going to get you do do something similar to what we did with NVIDIAInfo, but to do it with CCDInfo (which only uses the WinLibrary video library). Our aim here is to isolate just the WinLibrary functions to make sure that they work properly. Once we get that working, I'll then update NVIDIAInfo and fix that too. But for now we'll concentrate on CCDInfo.

So can you please do the following:

-  Download CCDInfo v1.7.9c from here and save it in your Downloads folder: [CCDInfo-v1.7.9c.zip](https://github.com/terrymacdonald/DisplayMagician/files/8885020/CCDInfo-v1.7.9c.zip)
- Open Windows Explorer.  Navigate to your Downloads folder. Right click on the CCDInfo-v1.7.9c.zip file you downloaded, and select 'Extract All', and click OK when the box popups asking you where to save it.
- Now open Powershell:  click on the Windows Start button and type the word 'powershell". The start menu should show the 'Windows Powershell' app. Click on that.
- Type the following into the Powershell window when it opens -  `cd "$HOME\Downloads\CCDInfo-v1.7.9"` and then press the enter key.
- The above command should move you into the same CCDInfo folder you just extracted CCDInfo into. Test that by typing in `.\CCDInfo.exe` and then press the enter key. You should see a help message. This is how we know where are in the right folder.

Now - copy and paste each of the commands below IN ORDER. It's really important to do it in order so that the log files contain the information I need in them. 

Create a surround display layout with some of your screens then:
- Save the first config as `.\CCDInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-surround-save.log"`
- Check if the first windows display config is equal with `.\CCDInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout, this time with individual triple screen:
- Save the second windows display as `.\CCDInfo save triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-triple-save.log"`
- Check if the second windows display config is equal with `.\CCDInfo equal triple.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `.\CCDInfo equal surround.cfg` (we want it to NOT be equal)

Next swap back to the surround display layout:
- Load the first windows display as `.\CCDInfo load surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-surround-reload.log"`
- Check if the first windows display config is equal with `.\CCDInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `.\CCDInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `.\CCDInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `.\CCDInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-triple-reload.log"`
- Check if the second windows display config is equal with `.\CCDInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `.\CCDInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `.\CCDInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- CCDInfo-surround-save.log
- CCDInfo-surround-reload.log
- triple.cfg
- triple-reload.cfg
- CCDInfo-triple-save.log
- CCDInfo-triple-reload.log

Lastly please take a screenshot or copy of your powershell commands so I can see what was typed.
- Grab a screenshot by pressing WindowsKey + Shift + S keys all together at the same time.
- Use you mouse to select the area of the screen you want to use
- You will have a Windows Action Notification popup saying you grabbed a screen shot. Click on that notification to open the screenshot.
- Click on the Image in the Screenshot application.
- Press Ctrl + C to copy it to Clipboard
- Come back to Github in your web browser
- Press Ctrl + V to paste the image into your Github comment.

This will give me all the information I need to know whether it worked! This will help me confirm that WinLibrary is ready to be integrated back into DisplayMagician. 

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
![Screenshot 2022-06-12 135431](https://user-images.githubusercontent.com/19865649/173234278-97ca7ac6-7978-4360-8293-0c1766e512a8.png)
![Screenshot 2022-06-12 135502](https://user-images.githubusercontent.com/19865649/173234279-f9970636-2264-46a0-bcab-d98e91e4c73f.png)
[CCDInfoTestResults.zip](https://github.com/terrymacdonald/DisplayMagician/files/8885858/CCDInfoTestResults.zip)

**Comment by terrymacdonald** [comment]
@TOCA2FREAK I've just realised I'm an idiot :). I got you to test surround configuration in the instructions using CCDInfo - and CCDInfo doesn't support NVIDIA Surround :eyeroll:

I'm so sorry about that! My only excuse it that it was late at night.... I just was going through your logs wondering why it didn't work, and then had a moment of clarity!

OK! So I'll update the instructions now, and get you to do a new set of instructions which will confirm that WinLibrary and WinLibrary only is working. Once we finish that testing, then we can move back to the NVIDIAInfo testing knowing that WinLibrary is working.

One things I really wanted to say was that it is so helpful for the whole DisplayMagician community to have you volunteering your time to help me out. Thank you so much for spending the time testing. I couldn't do what I do without the help of everyone. There are way too many different types of hardware combinations there is no way I could do all the testing myself. I need to have kind people such as yourself helping me in order to get these bugs squashed and to make DisplayMagician better.

**Now - some good news.** I found another few errors over the weekend when I was doing some programming, and I fixed them in CCDInfo v1.8.0, so, can you can you please do the following:

-  Download CCDInfo v1.8.0 from here and save it in your Downloads folder: [CCDInfo-v1.8.0.zip](https://github.com/terrymacdonald/CCDInfo/releases/tag/v1.8.0)
- Open Windows Explorer.  Navigate to your Downloads folder. Right click on the CCDInfo-v1.8.0.zip file you downloaded, and select 'Extract All', and click OK when the box popups asking you where to save it.
- Now open Powershell:  click on the Windows Start button and type the word 'powershell". The start menu should show the 'Windows Powershell' app. Click on that.
- Type the following into the Powershell window when it opens -  `cd "$HOME\Downloads\CCDInfo-v1.8.0"` and then press the enter key.
- The above command should move you into the same CCDInfo folder you just extracted CCDInfo into. Test that by typing in `.\CCDInfo.exe` and then press the enter key. You should see a help message. This is how we know where are in the right folder.

Now - copy and paste each of the commands below IN ORDER. It's really important to do it in order so that the log files contain the information I need in them. 

Create a cloned display layout with some of your screens then:
- Save the first config as `.\CCDInfo save cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-cloned-save.log"`
- Check if the first windows display config is equal with `.\CCDInfo equal cloned.cfg` (we want it to be equal)

Next create a second windows display layout, this time with individual triple screen:
- Save the second windows display as `.\CCDInfo save triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-triple-save.log"`
- Check if the second windows display config is equal with `.\CCDInfo equal triple.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `.\CCDInfo equal cloned.cfg` (we want it to NOT be equal)

Next swap back to the cloned display layout:
- Load the first windows display as `.\CCDInfo load cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-cloned-reload.log"`
- Check if the first windows display config is equal with `.\CCDInfo equal cloned.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `.\CCDInfo save cloned-reload.cfg`
- Make sure the second windows display config is NOT equal with `.\CCDInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `.\CCDInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-triple-reload.log"`
- Check if the second windows display config is equal with `.\CCDInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `.\CCDInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `.\CCDInfo equal cloned.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- cloned.cfg
- cloned-reload.cfg
- CCDInfo-cloned-save.log
- CCDInfo-cloned-reload.log
- triple.cfg
- triple-reload.cfg
- CCDInfo-triple-save.log
- CCDInfo-triple-reload.log

Lastly please take a screenshot or copy of your powershell commands so I can see what was typed.
- Grab a screenshot by pressing WindowsKey + Shift + S keys all together at the same time.
- Use you mouse to select the area of the screen you want to use
- You will have a Windows Action Notification popup saying you grabbed a screen shot. Click on that notification to open the screenshot.
- Click on the Image in the Screenshot application.
- Press Ctrl + C to copy it to Clipboard
- Come back to Github in your web browser
- Press Ctrl + V to paste the image into your Github comment.

This will give me all the information I need to know whether it worked! This will help me confirm that WinLibrary is ready to be integrated back into DisplayMagician. 

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
![Screenshot 2022-06-13 185812](https://user-images.githubusercontent.com/19865649/173415867-d41f8aab-9a15-439c-bfac-0532fab07e58.png)
![Screenshot 2022-06-13 185844](https://user-images.githubusercontent.com/19865649/173415870-f26406dd-e624-4380-948f-a4b6c9b62be8.png)
[CCDInfo-v1.8.0Testing.zip](https://github.com/terrymacdonald/DisplayMagician/files/8893389/CCDInfo-v1.8.0Testing.zip)

I'm glad to help squash these bugs as DisplayMagician is a godsend for me swapping between nvidia surround on and off again. :D

**Comment by TOCA2FREAK** [comment]
Sorry it's taken a while to get back to this.

I've just done what you suggested above and yes the primary monitor does change to the correct one when loading triple.cfg and then triple-primary.cfg.  So yes the new code is working! :D

**Comment by terrymacdonald** [comment]
Excellent! I will close down this issue, and see what else needs to be worked on to get v2.4.0 officially released!

**Comment by TOCA2FREAK** [comment]
This is still an issue with v2.4.1.1  :(

**Comment by terrymacdonald** [comment]
I have no idea how that could be as the WinLibrary code for setting the
primary monitor is exactly the same as the one that worked for you before!


Can you please try to recreate your display profiles, but this time please
wait 30 seconds after changing the display layout before saving each
display profile.

Can you please then do a couple of display profile changes, and then
generate a Support ZIP file for me please? Let's see what's going on. There
must be something causing this.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
![screenshot](https://user-images.githubusercontent.com/19865649/177016112-f637ae87-b251-427f-9022-7ce04b39890c.jpg)
[DisplayMagician-Support-20220702-2202.zip](https://github.com/terrymacdonald/DisplayMagician/files/9033713/DisplayMagician-Support-20220702-2202.zip)
Okay here is the support ZIP file along with screenshot showing Display 3 has been set as main even though windows shows Display 2 as main.  Just like in OP.

**Comment by terrymacdonald** [comment]
Did waiting 30 seconds before recreating the display profiles work? Or was
it still broken even after waiting 30 seconds?

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
Yeah I waited 30 seconds before recreating the display profile and still has the issue as in OP. :(

**Comment by TOCA2FREAK** [comment]
Hi Terry,

You are correct about the displays I'm using.

It's display 2 that is set to the main screen (middle screen) in windows display settings and the one I want to be the main display, but display 3 is actually the main display, so no it's not doing what I want it to.

Also when changing profiles I never have nvidia control panel or windows display settings open.  I only open them to check the profiles have changed correctly.

FYI sometimes displaymagician does work correctly and the middle monitor "display 2" does get set correctly as the main monitor.

**Comment by terrymacdonald** [comment]
Ok, so for confirmation, what are the names of the profiles that you change
from, and to? I want to make sure I'm following the right logs when you
move from profile #1 to profile #2 for a display that doesn't work.

Also, are you able to make a display profile without a cloned display in
it, and then test if that is able to set the primary display reliably. I
have a theory that it may be related somehow to having a cloned display in
the display profile. I remember in testing in the past I had a situation
where the primary display was changed when I set a cloned display in
windows setup. I wonder if that's somehow causing issues?

Actually, can you try to set up another test display profile that is the
same as your NVIDIA triple screens with cloned display, but can you do the
primary screen change as the last thing you do before you create the
display profile? I'm wondering if you make all the other settings changes,
and then set the primary screen right at the end of the process that will
record that correctly.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
So when changing to profile "NVIDIA Surround Off" is when it sets the wrong main monitor sometimes.  Changing to profile "Nvidia Surround On" I have no issues.

When you say make a profile without a cloned display in it what do you mean by that?

Lastly you ask to make another test display profile that is the same as my NVIDIA triple screen profile with cloned display.  I assume you mean setting windows display settings so all the monitors are a duplicate? (see screenthot)

![image](https://user-images.githubusercontent.com/19865649/178046596-d08dd8a4-9099-4923-bb21-7ccf1081f3be.png)

**Comment by terrymacdonald** [comment]
Sorry @TOCA2FREAK,

I sometimes use the internal programming names for functions rather than
what they are labelled in the Windows UI, as that's what I'm working with
most of the time! Sorry about that.

When I mean 'cloned' window I mean one that is a duplicate of another
window.

After thinking about it a bit more, I think I need you to create two
profiles with individual screens (no duplicate screens), and see if the
primary screen changing works then. It may be that the primary screens only
fail when leaving NVIDIA Surround mod, and that's what I'd like to test
next:

   - Using the triple individual screen as a base, use Windows Display
   Settings to move the middle screen slightly, and make the middle screen the
   primary screen. Do not use any duplicate screens in this profile.
   - Wait 30 seconds, then save this as a new profile called *Triple Test
   Middle* that has the middle screen as primary.
   - Close Windows Display Settings UI
   - Reopen Windows Display Settings, and change the primary screen to the
   left screen.
   - Wait 30 seconds, then save this as a new profile called *Triple Test
   Left *that has the left screen as primary.  Do not use any duplicate
   screens in this profile.
   - Close Windows Display Settings UI

Once you have those profiles created, please swap multiple times between
just those two profiles and see if the primary screen moves correctly.
Remember to either close Windows Display Settings UI (or you can just click
on a different part of windows Settings then swap back to the
Windows Display Settings UI as it forces a refresh that way).

What I am hoping will happen is that it will magically start swapping
primary displays with those two display profiles. I am hoping that we
figure out eventually that it is a problem that happens when leaving NVIDIA
Surround mode. Once I know how and when it consistently happens then I'll
be able to craft a workaround for that specific situation.

Also, please note we may have to move to testing the libraries themselves
using CCDInfo and NVIDIAInfo again, just to be sure that we're only testing
the video manipulation library functionality.... but we'll see how this
test goes first.

As always - thank you for all your testing! Finding bugs makes the software
better for everyone.

Thanks
*Terry*

**Comment by TOCA2FREAK** [comment]
Sorry been a while in getting back.  I've now reinstalled Windows to version 11.  I was on Windows 10 before.  I didn't do this due to DisplayMagician, it was just that my machine was due a spring clean and thought I would upgrade to Windows 11.

Since upgrading to Windows 11 I am no longer having this issue.  The only issue I do have though is that when changing from the "Nvidia Surround On" profile to the "Nvidia Surround Off" profile it can take quite some time to set my 4th monitor which is running off the motherboard HDMI port to be set correctly.  The screen will stay black for some time and then eventually turn on and get set.

**Comment by terrymacdonald** [comment]
Hi @Toca2freak,

Now that is very very interesting. I'll have to find a windows 10 box to
start testing with!

That slowness in changing windows and slowness in the windows taskbar
appearing seems to be a windows 11 thing. It does that on windows 11 for me
too, and my best guess is that it's the NVIDIA driver taking some extra
time to work on windows 11. It does eventually get there but takes about 20
seconds to complete the change. Nothing I can do to change that I'm afraid.

But the windows 10 thing is very interesting indeed. I'll try setting if I
have a windows 10 machine I can scrape up to do some testing on.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@TOCA2FREAK I *think* I may have found the issue.

There was an error that occurred in NvAPI_SetDisplayConfig when attempting to go from an NVIDIA Surround to a non-NVIDIA Surround setup on a machine that has multiple video cards installed in it. This is due to the fact that the NVIDIA driver only sees the displays connected to NVIDIA video adapters. 

The previous DM logic tried to set the DisplayConfig after switching to or from a Surround display profile, but this would fail when returning from a a Surround display profile on Win 10 devices. It appears that the NVIDIA driver AUTOMATICALLY disables all additional displays in windows when it returns from a Surround profile. This simple fact means that the DisplayConfig won't be applied properly, and it errors with an NVAPI_INVALID_ARGUMENT error. This doesn't actually matter though, as the WinLibrary comes to the rescue.

WinLibrary can see all the video adapters available, and so will turn the required displays back on and set them up just right! We *may* lose are some specific DisplayConfig parameters abeing set as part of this process, but I'm not totally sure about that as WinLibrary is basically feature parity with the DisplayConfig settings as far as I can tell.

The fix is to look specifically for the NVAPI_INVALID_ARGUMENT error when attempting to set the NvAPI_DisplayConfig, and if this happens we check if we were going from a surround profile to a non-surround profile. If that is true, then we simply ignore that error. WinLibrary then clears up that problem and everything proceeds as normal.

This should (fingers crossed) fix this issue once and for all!

This change also makes it far faster to grab and set the taskbar settings from registry, though this logic may not detect some Windows 10 formats which appear to be LOCALDISPLAY(\d,\d,\d\d) settings which I've never seen before. It should be generally much faster and more reliable.

Anyway - please download this test version 2.4.1.14 from here and install it, and please tell me if it now works: [DisplayMagicianSetup-v2.4.1.14.zip](https://github.com/terrymacdonald/DisplayMagician/files/9111122/DisplayMagicianSetup-v2.4.1.14.zip)

The thing that really unlocked this was the confirmation that you had the issue on Windows 10, and another user Whitestar also had the same issue on Win 10 too. It seems to be related to how the NVIDIA Driver reacts on Windows 10, so hopefully this changes makes it all better.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
v2.4.1.14 seems to be working fine on Windows 11.  So far no issues. :)

**Comment by terrymacdonald** [comment]
Excellent news. I've asked Whitestar to also test that same version as he
is on windows 10 still. That will give me some comfort that I've fixed the
problem if it works for them.

I'll keep this issue open until they respond that it works, and I'll try
some more tests on another windows 10 machine I've got.

If it all works I'll close this issue.

Thanks
Terry

**Comment by terrymacdonald** [comment]
And it is confirmed working for @Whitestar too, so I'm closing this issue! Excellent news.
