### ISSUE TITLE
Profiles stop working after a while

### ISSUE THREAD

**Issue by Horcon** [terrymacdonald/DisplayMagician#12]
**Describe the bug**
The earlier bug seems to have returned to me after I rebooted (due to installing an audio driver, Creative Sound BlasterX G6)
After 1.0.5 was released I set the logging to debug to ensure that if the bug comes back, I could provide more information for a fix. At first I thought this was caused by the computer rebooting, but after a manual reboot the newly created profile works just fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a profile
2. Wait a couple of days
3. Profile cannot be used ("This Display Profile can't be used as not all Displays are connected.")

**Expected behaviour**
Profile should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/8670196/116149892-fa793800-a6e2-11eb-9229-b9571fa3e042.png)

**Reporting Logs**
[After reboot.log](https://github.com/terrymacdonald/DisplayMagician/files/6380260/After.reboot.log)
[DisplayProfiles_1.0.txt](https://github.com/terrymacdonald/DisplayMagician/files/6380262/DisplayProfiles_1.0.txt)

**Enviroment (please complete the following information):**
Windows 10 Enterprise with pretty much all recent patches.

**Additional context**
After some manual debugging, I came across some more information that I'm attaching here. First is the log that I think is not that important, but the second are the three display profiles that I have right now. The v2 profiles are what worked until now, while v3 is the new one. Note that the old profiles have # in the Serial field, while the new profile has the Serial 00-00... in it. This is what is causing the entire bug by the looks of it, as when I copy pasted the v3 segment into the v2 segment in the profile, the profiles work again. I managed to both switch to the Surround v2 and back to Normal v2 profiles without issue.

**Comment by terrymacdonald** [comment]
Hi @Horcon,

It looks from your logs that the new "protection" I put in place to handle NVIDIA driver errors is kicking into place. I've been hearing from people that the new 466.11 NVIDIA driver has been causing issues when using NVIDIA RTC 2080Ti cards, and that DisplayMagician was crashing. You can see more about that in issue #7 if you're interested.

The issues is unfortunately upstream from DisplayMagician so I could not fix it. It is either the NVIDIA driver itself (most likely), or the NvAPIWrapper library we use (less likely). The best I could do was provide a workaround, and that's what I attempted to do in DisplayMagician v1.0.5.

Whenever we get an exception interrogating the NVIDIA card, DisplayMagicin generates a "#". So I can see from your logs that your NVIDIA video card driver does not provide a serial number for your TU102-A card (which I believe is an NVIDIA RTX 2080Ti card IIRC). DisplayMagician v1.0.5 instead has generated a different ProfileDisplayIdentifier to avoid crashing and exiting.

I actually mentioned what you need to do to workaround this in the DisplayMagician v1.0.5 release notes here: https://github.com/terrymacdonald/DisplayMagician/releases/tag/v1.0.5, though my instructions weren't that clear on second re-read.

The latest NVIDIA 466.11 drivers don't correctly get hardware information from the NVIDIA RTX 2080Ti video cards, so I've had to build some protection around the information gathering code to attempt to keep this application working even if the NVIDIA code fails.
If you have the NVIDIA driver issue then you will need go into each of your Display Profiles and save them (press the rename button). You will then need to go into each of the shortcuts and select that same Display Profile, then save them too. This will use the new profile matching logic and will get you back up and running. Note: When NVIDIA realises and fix their driver you will need to perform these steps again.

**To fix the problem:**

- Deleted the old Display Profiles
- Recreate each DisplayProfile again from scratch
- Go through each of your Game Shortcuts to use one of the newly created Display Profiles.

Unfortunately that's the only way to regenerate the DisplayProfileIdentifiers and make everything match up again :(.

The more annoying thing, is that you'll need to do it all again when NVIDIA fixes their display driver as the fix will change the DisplayProfileIdentifiers again, and so none of the DisplayProfiles will match. Really sorry about that but there isn't anything I can do about it. I've fixed it as best I could.

**Comment by terrymacdonald** [comment]
As I can't fix this due to this being an upstream issue I'll be closing this issue. Hopefully the instructions I provided earlier will help you fix this @Horcon . Really sorry there isn't another way around it :/.
