### ISSUE TITLE
"Update Check Failed" error even when there's no active network adapter available

### ISSUE THREAD

**Issue by CodeContributorX** [terrymacdonald/DisplayMagician#120]
**Describe the bug**
"Update Check Failed" error every time DisplayMagician starts.
Even when there is no active network adapter available in Windows.
"Upgrade DislayMagician [..]" option **disabled**

**To Reproduce**
Steps to reproduce the behaviour:
1. Disable all network adapters
2. Start DisplayMagician
3. Observe the error

**Expected behaviour**
No error when "Upgrade DislayMagician [..]" option disabled.

**Screenshots**
![2022-06-12_11-55-33-741](https://user-images.githubusercontent.com/60100420/173228373-b000930f-bd3a-44dd-9152-835681ce97e8.jpg)
![2022-06-12_12-01-31-808](https://user-images.githubusercontent.com/60100420/173228374-63146dc5-6bf4-4572-8518-c829c7183a3b.jpg)

**Setting:**
```
{
  "StartOnBootUp": false,
  "ShowSplashScreen": false,
  "UpgradeToPreReleases": false,
  "MinimiseOnStart": false,
  "InstalledDesktopContextMenu": false,
  "LastMessageIdRead": 0,
  "MessagesToMonitor": [],
  "LogLevel": "Trace",
  "HotkeyMainWindow": 0,
  "HotkeyDisplayProfileWindow": 0,
  "HotkeyShortcutLibraryWindow": 0
}
```

**Log:**
2022-06-12 13:21:51.3733|DEBUG|DisplayMagician.Program|Program/StartUpApplication: Starting
2022-06-12 13:21:51.3973|ERROR|DisplayMagician.Program|Program/ShowMessages: Exception while trying to load the messages index from https://displaymagician.littlebitbig.com/messages/index_2.0.json.
2022-06-12 13:21:51.3973|WARN|DisplayMagician.Program|Program/AutoUpdaterOnCheckForUpdateEvent - WebException - There was a problem reaching the update server.
2022-06-12 13:21:51.4183|TRACE|DisplayMagician.UIForms.MainForm|MainForm/MainForm_Load: Main Window has loaded.
2022-06-12 13:21:51.4183|DEBUG|DisplayMagician.ProgramSettings|ProgramSettings/SaveSettings: Attempting to save the program settings to the C:\Users\<username>\AppData\Local\DisplayMagician\Settings_2.0.json.

**Enviroment:**
 - Windows 11
 - DisplayMagician Version 2.3.1.60
 - Video Card: nVidia GeForce RTX 3070
 - 3 x Samsung SyncMaster 2443
 - Driver Date: 19.05.2022
 - Driver Version: 30.0.15.1295
 - Windows Version: 21H2, Build 22000.708

**Comment by terrymacdonald** [comment]
Hi @CodeContributorX , thanks for logging the issue.

DIsplayMagician updating works fine for others with that exact same version, so I wonder what is happening here. I wonder if it's something about the particular previous versions that you've upgraded from. Maybe some files weren't migrated properly during a previous upgrade.

Can you please generate a Support ZIP File for me, and then upload it here? You can do that in the settings window. That will let me see the full logs and I can try and figure out where the logic is failing.

Thanks
Terry

**Comment by CodeContributorX** [comment]
Hi Terry,

Thanks for quick reply. Not sure if I described the issue clear enogh in the bug report.
The problem is not that updating does not work. My problem is that DisplayMagician tries to connect to internet when there's no internet connection. The program tries to connect even when all network adapters are switched off.

Is it possible to check internet connection in program code before update event to avoid the error?

I guess full log is not necessary in this case. Hope this exclanation is clearer now.

Regards

**Comment by terrymacdonald** [comment]
Hi,

Yeah I got that. The files are accessible as far as I can tell.
DisplayMagician does a lot of logging, so if you could go into settings,
make sure the living level is set to TRACE level, and then click on Create
Support ZIP File it would really help me understand where the error is in
the code.

In other words, the logs help me troubleshoot the faulty logic, or helps me
realise what additional logic needs to be added to cope with the situation
you're describing.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @CodeContributorX,

I've stepped through right now using a debugger, and the update mechanisms work fine for me and my system.

Firstly, it connects to http://displaymagician.littlebitbig.com/update/update_2.0.json and download the JSON there:

````
{
  "version": "2.3.1.60",
  "url": "https://github.com/terrymacdonald/DisplayMagician/releases/download/v2.3.1/DisplayMagicianSetup-v2.3.1.60.msi",
  "changelog": "https://github.com/terrymacdonald/DisplayMagician/releases",
  "mandatory": {
    "value": false,
    "minVersion": "0.1.0.0",
    "mode": 0
  },
  "checksum": {
    "value": "211FD8EB7720F4B215C61BCE74A063290289C9E3C6CF4847DA20BF70B1B990F7",
    "hashingAlgorithm": "SHA256"
  }
}
````

It then parses the file, and checks to see if there is a newer version than the current version. Seeing as you are using 2.3.1.60, it *should* see the version 2.3.1.60 in the file above, and it will recognise it is the same version and skip performing an update. That is exactly what my DisplayMagician does when I step through it on the debugger locally.

So my first thought is that maybe something is preventing your computer from accessing http://displaymagician.littlebitbig.com/update/update_2.0.json ? 

If not then one of the following things could be to blame:
- You may have filtering on your internet from your Antivirus. This may be preventing the download from occurring over HTTP (which is unfortunately the only thing that works for displaymagician.littlebitbig.com domain :( ).
- The Windows subsystem may have been updated to prevent HTTP only connections, which the first redirect is currently using; all subsequent connections are over HTTPS.
- You may have some sort of DNS filtering for uncommon domain names through your Internet Provider
- There may be transient network issues affecting routing to github (displaymagician.littlebitbig.com is hosted at github.com)

My Windows 11 is patched to the latest versions, and it can connect ok, so it needs to be something specific to your situation which is affecting the communication and preventing it from happening.

Are you able to access http://displaymagician.littlebitbig.com/update/update_2.0.json from your web browser and see the file contents I've shown above? 

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @CodeContributorX,

It was way easier to add the network detection check than I thought. I've added it to the v2.4.0 codebase already (you can see the commit above) so it will be part of the v2.4.0 release. 

I'll close this issue now so I can keep track of the work I still have to do. Please feel free to reopen if I still haven't quite understood the issue you were describing to me.

Thanks
Terry

**Comment by CodeContributorX** [comment]
Hi Terry,

I fully agree. It is not a bug :) Sorry for confusion.
After second thought I also agree that it is usefull to know that there's a problem with internet connection.

Thank you for incorporation the option.

Regards
