### ISSUE TITLE
Restore previous window position on profile switch

### ISSUE THREAD

**Issue by waitwhereami** [terrymacdonald/DisplayMagician#124]
**Is your feature request related to a problem? Please describe.**
First off, I love the software so far. It fixes a problem I didn't know I had. Great work! I did have one suggestion for an improvement, however. When switching between NVIDIA surround and my standard two monitor extended desktop I've noticed any open windows lose their positioning. It's not a huge deal to put them back where they came from thanks to Power Toys Fancy Zones, but a way to automagically return them would be amazing. Not being familiar with your code, I'm not even 100% sure if it's feasible, but it would be awesome.

**Describe the solution you'd like**
On switching Display Profiles, the software would save the profile name along with the window IDs and locations of any open windows. When switching back to the original Display Profile, the software would detect a saved log of windows and attempt to return them to their original locations.

Bonus points for mathing out where in the new profile open windows would be located and placing them there in advance. For instance if a window is located at 100, 100 on monitor 2, when switching to NVIDIA surround, placing it at 2020, 100 should keep it near the same location.

**Describe alternatives you've considered**
I don't think any open source software exists to do this in windows. DisplayFusion can do it.

**Additional context**
Again this is a strictly nice-to-have, but it would be a killer feature in my book.

**Comment by terrymacdonald** [comment]
@waitwhereami Funny you should log this. I actually just got annoyed by this very thing myself last week, and so added a similar feature into DisplayMagician v2.4.0 (which is currently in testing). 

It's unfortunately nowhere near as fancy as what you suggested above, but it does work. It simply figures out where the middle of the primary monitor is, and centers itself on that. This ensures that it will work when it switches from surround/eyefinity screens, and triple monitors and cloned screens. All of those change the screen coordinates by too much for me to do anything trickier than the above.

So, as I have already accidentally implemented something similar, I'll close this enhancement issue so I can keep track of the work I still need to do.

If you have any other really cool ideas feel free to log them, and I'll try and figure out if they are feasible.

Thanks
Terry
