### ISSUE TITLE
v2.4.0 doesn't work on Win10 (with old configs)

### ISSUE THREAD

**Issue by A0L0XIIV** [terrymacdonald/DisplayMagician#128]
**v2.4.0 doesn't work on Win10 (with old configs)**
After updating it from 2.3.1 to 2.4.0 DM doesn't work/launch.
After running the executable, it starts the process. However, as soon as I started to interact with its GUI (system tray or right-click menu profile change) it goes away (system tray icon) and the process stops/dies.

**Tried these methods**
- Updated from 2.3.1 -> 2.4.0, restarted my PC. tried to launch DM, but didn't launch
- Restarted one more time, no effect
- Tried to repair DM using the setup, but no effect
- Removed and installed DM using the setup, restarted PC, didn't work
- Repaired one more, no effect
- The only way that works with v2.4.0 : renamed the folder in the AppData so the new DM couldn't use my old 2.3.1 configs. This seems to work, so my guess is something in that folder crashes the new version. (Attached the log and all JSON files below)
- Also, v2.3.1 still works (after re-installing it).

**Expected behaviour**
v2.4.0 should work like the previous 2.3.1 (after updating it).

**Reporting Logs**
[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/9024635/DisplayMagician.log)
[profile_shortcut_setting.zip](https://github.com/terrymacdonald/DisplayMagician/files/9024637/profile_shortcut_setting.zip)
[dm_gui_error.txt](https://github.com/terrymacdonald/DisplayMagician/files/9024674/err.txt)

**Enviroment (please complete the following information):**
 - Windows Version: Win10 21H2
 - DisplayMagician Version 2.4.0
 - Video Card: EVGA NVIDIA GTX3080
 - Number and make/model of monitors: 1x Samsung LC27G7xT, 1x Asus VG27AQL1A, 1x Acer V277U
 - Date of last video driver update: 2022-06-30 (516.59)
 - Date of last windows update: 2022-06-30 (OS build 19044.1806)

**Comment by terrymacdonald** [comment]
Hi,

Was that after creating brand new display profiles? DisplayMagician needs
new display profiles in order to work.

Please create a Support ZIP File from the settings button in the main page,
and upload it here. That will let me see your configuration and the log
files too.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@A0L0XIIV I think I found the issue:

````
022-06-30 22:13:10.6036|ERROR|DisplayMagician.Program|Program/Main general exception during app.Execute(args): |EXCEPTION OCCURRED :System.NullReferenceException: Object reference not set to an instance of an object.
   at DisplayMagician.Utils.CenterOnPrimaryScreen(Form frm)
   at DisplayMagician.UIForms.MainForm..ctor(Form formToOpen)
   at DisplayMagician.Program.<>c__DisplayClass32_0.<Main>b__5()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DisplayMagician.Program.Main(String[] args)
````

It looks like it's the new centering logic. It fails to take into consideration running it without a form, as happens from a Desktop Shortcut or system tray.

I'll hopefully have a fix out shortly.

Thanks
Terry

**Comment by A0L0XIIV** [comment]
Hi Terry,
Yes and no. It wasn't working either before or after the new profile creation.
The only solution that worked for me was removing the DisplayMagician file in the AppData (in my case, I just renamed it to something different). So, probably something in my old settings, profiles or shortcuts was causing this issue. 
I am glad you found the issue.
Thanks

**Comment by terrymacdonald** [comment]
@A0L0XIIV Are you around for the next 30 mins?  I should have a fix out by then and it would be cool to get you to test ASAP. I'd love to get this fixed before everyone starts using 2.4.0 over the weekend.

I'll drop the new fixed version as soon as I can (next 10 mins or so).

Thanks
Terry

**Comment by A0L0XIIV** [comment]
Sure, I can test the new release with my old settings. I haven't deleted them yet.

**Comment by terrymacdonald** [comment]
@A0L0XIIV Here we go, hot off the press! This adds a lot of extra error checking around the new window centering code to (hopefully) avoid this issue. I couldn't see any other errors in your log file, so fingers crossed this works! 🤞 

[DisplayMagicianSetup-v2.4.1.1.zip](https://github.com/terrymacdonald/DisplayMagician/files/9025059/DisplayMagicianSetup-v2.4.1.1.zip)

Please report back with whatever you find, good or bad.

If there are any problems, please create a Support ZIP File once you've tested it (Main Window > Settings button >Create Support ZIP File) and upload it here and I'll do some more digging.

Thanks!
Terry

**Comment by A0L0XIIV** [comment]
It works!
I re-installed v2.3.1.60, changed my settings folder to the old one, and installed the new v2.4.1.1.
Now I can access the GUI with my old profiles and shortcuts.

Thanks for the help and for solving the issue lighting fast! 
Closing the issue.

**Comment by terrymacdonald** [comment]
Best news ever! Thanks to YOU for testing so quickly for me! We just avoided impacting about 1500 people's weekends. That's a good thing.

Thanks
Terry
