### ISSUE TITLE
ArgumentOutOfRangeException when creating a new game profile

### ISSUE THREAD

**Issue by ngoetje** [terrymacdonald/DisplayMagician#13]
**Describe the bug**
Unhandled exception when adding a new game profile.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Application Window
2. Click on 'Game Shortcuts'
3. Click on 'New'

**Expected behaviour**
"Wizard" for adding a new game shortcut opens

**Reporting Logs**
As this does not relate to the graphics/monitoring configuration of the system, I do not provide an "Helios" log file..

The message windows says:
`System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: i
   bei System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   bei DisplayMagician.GameLibraries.UplayLibrary.LoadInstalledGames() in H:\vscode-projects\DisplayMagician\DisplayMagician\GameLibraries\UplayLibrary.cs:Zeile 591.
   bei DisplayMagician.GameLibraries.UplayLibrary.get_AllInstalledGames() in H:\vscode-projects\DisplayMagician\DisplayMagician\GameLibraries\UplayLibrary.cs:Zeile 92.
   bei DisplayMagician.UIForms.ShortcutForm.ShortcutForm_Load(Object sender, EventArgs e) in H:\vscode-projects\DisplayMagician\DisplayMagician\UIForms\ShortcutForm.cs:Zeile 928.
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Enviroment:**
 - Windows Version: Win10
 - Version 1.0.5

**Additional context**
I was able to work around the error and created a fork and a pull request. It crashes when looking for registry entries for games that are not installed anymore.

**Comment by terrymacdonald** [comment]
Unfortunately the fix provided causes issues accessing any Uplay games and breaks the Uplay Library parsing. I will attempt to craft a different fix to avoid the error while maintaining the UplayLibrary parsing...

**Comment by terrymacdonald** [comment]
OK - I've spent most of the day coding and testing, and I think I have it working now. It properly loads games in Steam, Uplay(Ubiconnect) and Origin game libraries, and it also logs OriginLibrary events properly to the DisplayMagician.log file. I also greatly enhanced the verbosity of the logged events when in trace mode for the logging level for the OriginLibrary. Should help greatly.

So, I will shortly be creating a test release to see if that fixes your issue... or at least will help me figure out what is happening via the DisplayMagician.log file. I'd really appreciate it @ngoetje if you could test the test release to see if that works for you?

Please:

- Uninstall DisplayMagician v1.0.5. It will leave your settings there.
- Unzip and install the DisplayMagician v1.0.5 Test release attached to this post.
- If it works great!
- If it doesn't work then please perform the steps below to set the logging level to Trace, restart DisplayMagician and try to open a shortcut. Then upload the DisplayMagician.log file here.

[DisplayMagicianSetup-v1.0.5.1-test.msi.zip](https://github.com/terrymacdonald/DisplayMagician/files/6403303/DisplayMagicianSetup-v1.0.5.1-test.msi.zip)

**NOTE:** When you do test this release, please make sure that you click on the 'Settings' button and select the "Full Application Trace (very large)' setting, as that will give me full details of what is happening. Please then upload the DisplayMagician.log file into this issue. You can find the DisplayMagician.log file in the C:\Users><username>\AppData\Local\DisplayMagician\Logs folder.

**Comment by ngoetje** [comment]
Looks good, there is no error shown and I am able to add new game profiles. I attached the trace log recorded while adding a new game profile just for documentation purposes anyway. 
[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/6403381/DisplayMagician.log)

Great tool and and thank you very much for maintaining and developing it!

**Comment by terrymacdonald** [comment]
Awesome! Thank you so much for testing. I've now rolled a proper release, and now everyone else can enjoy the results of your bug finding. 

Thanks again for logging this issue.  I can't test every type of setup and configuration, so I really do rely on people helping me out. It really does help.

**Comment by ngoetje** [comment]
Sure, no problem, thanks for properly fixing the bug! Cheers!
