### ISSUE TITLE
SimHub does not close after game has closed

### ISSUE THREAD

**Issue by deancommasteven** [terrymacdonald/DisplayMagician#135]
SimHub is not closed after game has closed.

Steps to reproduce the behaviour:
1. Create shortcut including launching SimHub before game
2. Launch shortcut
3. Close game that was launched
4. SimHub does not close (All other apps do close)

**Expected behaviour**
SimHub closes after game is closed

**Screenshots**
![image](https://user-images.githubusercontent.com/25689810/183309033-e06af12b-a5dc-44aa-8f0c-c295dd854ca1.png)

**SupportZip**
[DisplayMagician-Support-20220807-1602.zip](https://github.com/terrymacdonald/DisplayMagician/files/9277421/DisplayMagician-Support-20220807-1602.zip)
(I didn't see any logs pertaining to SimHub not quitting in this support bundle)

**Enviroment:**
 - Windows Version: Windows 11 Pro 21H2
 - DisplayMagician Version: 2.4.1.14 (Not new to this version, behavior exhibited in previous version also)
 - Video Card: RTX 3080 Ti
 - Number and make/model of monitors: 3x AOC CU34G2X
 - Date of last video driver update: 2022-06-28 v516.59
 - Date of last windows update: 2022-07-24

**Additional context**
If I quit SimHub using my previous method, a bat file, I must pass the /f argument to force close. However, I also have to pass this to Trading Paints in the bat file, but DisplayMagician closes it without issue.

**Comment by terrymacdonald** [comment]
Hi,

SimHub can't be closed easily unfortunately as it is designed to be run in
the background continuously. I would suggest adding the following command
to your 'Stop Program' for the iRacing + Extras (in the 5. what happens
afterwards section):

"C:\Program Files (x86)\SimHub\SimHubWPF.exe" -exit

You can find more information about the SubHub commands here:
https://github.com/SHWotever/SimHub/wiki/Command-line-interface . Hope that
helps!

Thanks
*Terry *

**Comment by deancommasteven** [comment]
This works perfectly. Thanks!
