### ISSUE TITLE
CTD with 1 HDMI, 1 HDMI Dummy, 2 x USB via Dock

### ISSUE THREAD

**Issue by kevnikos** [terrymacdonald/DisplayMagician#145]
**Describe the bug**
I've tried v2.3 and 2.4 and both crash to desktop after I get profiles setup.  Switching to a configuration involving the USB monitors does not work.

My setup is:
- 1 monitor on HDMI
- 1 HDMI dummy dongle
- 2 x USB monitors via Dell D6100 dock (DisplayLink)

**To Reproduce**
1. Setup profiles
2. Reboot
3. Try to switch to profile involving docked monitors

**Expected behaviour**
Should switch to the profile selected.

**Screenshots**

**Reporting Logs**
If DisplayMagician starts:
- Open DisplayMagician and perform whatever actions are needed to make the bug occur.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Come back here, and upload the Support Zip File through your web browser and attach it to this issue.

*DM crashes, cannot obtain.

If DisplayMagician does not:
- Open a terminal window and run `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` to create a TRACE-level DisplayMagician.log file.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- Also attach the following files to this issue:
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_2.1.json` 
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json`
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`

Zipped the whole folder.
[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/9500630/DisplayMagician.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Win 10 Home 21H2  (19044.1889)
 - DisplayMagician Version 2.4.1.14
 - Video Card: Nvidia GTX 1060 3GB
 

Number and make/model of monitors: 
   - 2 x HP 24es     (through Dell D6100 USB3 DisplayLink Dock)
   - 1 x Samsung 24"  (direct HDMI port)
   - 1 x HDMI Dummy Plug   (direct HDMI port)
 - Date of last video driver update: 2022-09-01
 - Date of last windows update: 2022-09-01

**Additional context**
Really hoping I can get this utility working!   Such a pain to switch stuff manually!

**Comment by terrymacdonald** [comment]
Hi @kevnikos,

Thanks for logging an issue. I've not had anyone with a DisplayLink Dock do any testing as yet, so I'm not surprised this could be an issue. I've no understanding of DisplayLink and how it affects Windows, or even how the driver subsystem works. It would require quite a lot of investigation to try and figure out what has gone wrong here. It could take a month or two of testing before we can find out what is wrong. Are you available to do testing over that timeframe?

My availability will be a bit patchy over the next 3-6 months or so, so I'd like to apologise up front for any delays from my side. I won't have quite as much time available to spend on DisplayMagician as I have had over the past few years.

With all that said, I'll have a look at the logs you sent through, and see what I can find.

Oh - one more question. What is the HDMI Dummy Plug you mentioned? I don't know what that is. Can you please provide a link to an online site that describes what that is?

Thanks
Terry

**Comment by dev1981** [comment]
hi folks, i am using as well a DisplayLink device, not in a DELL docker but in a fujitsu one. I dont have any crashes in generall but as well some issues during profile switch. In my case the two displays which are connected getting not connected during profile switch. I have to connect them manually after i switched my 3 main displays to NV surround. Afterwards the layout fits. 
As additional hint, the NV control panel doe snot recognize the additional Displays but Windows DP manager does.

**Comment by terrymacdonald** [comment]
Yeah, the NVIDIA API only really knows about devices connected through the
NVIDIA device.  The windows CCD API is the one that works across all
display drivers.

I'll need to do some research as to how the Display Link architecture
works, so I can tell if DisplayMagician is likely to work with it. To be
honest I'm surprised that USB-C devices work at well as they do it as I
don't have anything to test with so haven't been able to do the usual
testing I do. So I'm not overly surprised that the display link stuff
doesn't work.

I do want to warn you both I may not be able to get it to work. In my
NVIDIA Optimus research I couldn't get that going, so we may hit the same
issues here. But I'll give it a go at least!

Thanks
Terry

**Comment by dev1981** [comment]
as i said, in general it is working! 4 me its only the connected / disconnected state is not stored / handled correctely.

**Comment by kevnikos** [comment]
Hi Terry, happy to help with testing for sure whenever is convenient for
you.

The dummy plug I use to simulate a monitor being connected as I use
Moonlight <https://moonlight-stream.org/> for remote gaming sometimes and I
don't want to leave my monitors powered on.   This allows the software to
capture the screen otherwise it cannot.  Here's the specific one I'm
using... but there are tons of them.
1-Pack A ADWITS 4K 2K 1080P 30Hz to 60Hz Support HDMI Display Emulator DDC
EDID Headless Ghost Monitor Adapter Dummy Plug, New Version Highest
***@***.*** in Gold Color : Amazon.ca: Electronics
<https://www.amazon.ca/gp/product/B0788HYC1S/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1>

**Comment by terrymacdonald** [comment]
@kevnikos Can you please remove the HDMI Dummy Plug, and then create two new test profiles that don't use the HDMI Dummy Plug, and see if you still get CTDs? I'd like to eliminate the HDMI Dummy plug from the equation, and the best way to do that is to remove the device.

Thanks
Terry

**Comment by kevnikos** [comment]
Yes, will do that tonight and check it out.

**Comment by terrymacdonald** [comment]
Hi @kevnikos,

Any news about the HDMI Dummy plug? Did that eliminate the issue?

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @kevnikos,

Did removing the HDMI dummy plug fix the issue? As it's been a while, I'll close this issue for now. You'll be able to reopen it when you reply, and then we'll kick off some more investigation.

Thanks
Terry
