### ISSUE TITLE
Display orientation not detected / saved

### ISSUE THREAD

**Issue by Kilcekru** [terrymacdonald/DisplayMagician#153]
**Describe the bug**
I have 2 displays which can rotate. I would like to have different display orientation in different profiles. But no matter my current configuration Display Magician always shows all display in landscape orientation.
I am not sure if this is a bug, a missing feature or if i am doing something incorrect.

**To Reproduce**
Set any display to portrait orientation. Display Magician does not recognize this.

**Expected behaviour**
Profiles store correct display orientation and set the orientation correctly on profile switch

**Screenshots**
![ScreenSetup](https://user-images.githubusercontent.com/8425613/198312547-237b156e-24c4-49a1-93a6-80ffbb9dadbc.png)
![DisplayMagician](https://user-images.githubusercontent.com/8425613/198313113-9c48aa9e-d43d-43da-ae45-1d000918238e.png)

[DisplayMagician-Support-20221027-1615.zip](https://github.com/terrymacdonald/DisplayMagician/files/9880223/DisplayMagician-Support-20221027-1615.zip)

**Enviroment (please complete the following information):**
 - Windows Version: 10
 - DisplayMagician Version: 2.4.1.14
 - Video Card: NVIDIA GeForce GTX1070
 - Date of last video driver update: 2022-10-27
 - Date of last windows update: 2022-10-27

**Comment by terrymacdonald** [comment]
@Kilcekru This is all very weird. Your support ZIP File doesn't have any logs in it, only Settings and Display Profiles. Very odd.

I can only see one Display Profile there. Did you have two Display Profiles created originally? 

I think you might be the first person to actually use the same displays to swap between portrait and landscape mode. I don't think I've every tested it ever! I'm not even sure that the information is in the data that I grab from Windows API or NVIDIA NvAPI. I'll need to go and look.

Can you please do some testing for me?

- Please setup Windows Display Settings to portrait mode, then apply it
- Go back to DisplayMagician and save the display profile as 'Portrait'
- Please setup Windows Display Settings to landscape mode, then apply it
- Go back to DisplayMagician and save the display profile as 'Landscape'
- Try to swap from Landscape to Portrait Display Profiles
- Try to swap from Portrait to Landscape Display Profiles
- Go into the Settings page and then save a new Support ZIP File.
- Upload the Support ZIP File here using your web browser.

Hopefully that will give me some more information  about what is happening here. We may also need to do some testing using NVIDIAInfo, which is a standalone command line program I wrote to exercise the NVIDIALibrary and WinLibrary functions I wrote. We may need to do some testing using that program to isolate the issue.

Are you ok with doing the above testing for me?

Thanks
Terry

**Comment by Kilcekru** [comment]
@terrymacdonald Thank you so much for your help.

I tried multiple things before. When i created the Support ZIP I had only 1 profile left.

I followed you steps to create the profiles and now it actually worked. I have no idea, what i did different this time.
Here is the Support file:

[DisplayMagician-Support-20221108-2238.zip](https://github.com/terrymacdonald/DisplayMagician/files/9965470/DisplayMagician-Support-20221108-2238.zip)

I also tried and set it up, like i want to have it. Although i have tried this and it never worked, now it does.

The thumbnails of the profiles are still wrong (all display are always shown in landscape mode), but when i apply it, it does the correct thing. I have no idea, why it didn't work before.

Thanks, Kilcekru

**Comment by terrymacdonald** [comment]
Hi Andreas,

Sounds like I still have a bug to fix in the display icon part of
DisplayMagician. I'll try doing some testing over the next few weeks and
see if I can fix that display icon issue. I'll then need to publish a new
release.

Thanks
*Terry *

**Comment by terrymacdonald** [comment]
@Kilcekru I have fixed the portrait display profile icon issue in the codebase for NVIDIA and Windows, but I've run out of time today to do the AMD. I'll see if I can spare some time shortly to get that working as well, and then I'll bake another test release, and then I'll drop it in this issue for you to test. Hopefully that should show everything working as it should have done!

Thanks for bringing this to my attention so I could squash this bug.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Kilcekru I have fixed the AMD rotation code now so that it also understands and shows rotation properly. Please note that I do not have an AMD card, so I will need to get another person to test that part before I am ready to release the updated DisplayMagician version to everyone.

I have created a test version of DisplayMagician that should now allow you to rotate your displays and have it show up. Can you please download, unzip and install this version to make sure it works? Please report back here in this issue so I know even if it works fine, so I know.

[DisplayMagicianSetup-v2.5.0.337.zip](https://github.com/terrymacdonald/DisplayMagician/files/10312741/DisplayMagicianSetup-v2.5.0.337.zip)

Thanks
Terry
