### ISSUE TITLE
Sometimes failing to switch to correct PC resolution@hz - chooses TV resolution instead

### ISSUE THREAD

**Issue by GibbousWaximus** [terrymacdonald/DisplayMagician#158]
**Describe the bug**
The three profiles I switch between are:

[Main]
Primary monitor. HDMI 1->LG TV 1. PC Resolution 3840x2160@120hz w/gsync
Secondary monitor. Displayport1->HDMI adapter->Receiver1->Dell monitor. 1920x1080@60hz

[HomeTheater]
HDMI 2:->Receiver2->LG TV 2. Resolution 4k x 2k, 3840x2160@60hz.

[DellOnly]
Secondary monitor. Displayport1->HDMI adapter->Receiver1->Dell monitor. 1920x1080@60hz

The issue is that sometimes when switching from one of the other profiles to the Main profile, the resolution of the primary monitor gets set to 4k x 2k, 3840x2160@60hz instead of the "PC resolution" @ 120hz.

**To Reproduce**
I am not sure how to reliably reproduce this behavior. Switching profiles to Main and getting the correct PC resolution works for a while and then it doesn't, and I'm at a loss to identify a common cause.

**Expected behaviour**
When switching to the Main profile, I expect the primary monitor to switch to the PC resolution 3840x2160@120hz instead of the Ultra HD,HD,SD resolution of 4k x 2k, 3840 x 2160@60hz.

**Screenshots**
![Correct_resolution](https://user-images.githubusercontent.com/918200/200186549-d2ba1997-4ae7-4e3f-beb2-b04875380a2c.png)

![Incorrect_resolution](https://user-images.githubusercontent.com/918200/200186712-0d8a5728-a470-462d-abb1-caa8d6d11cb2.png)

**Reporting Logs**
[DisplayMagician-Support-20221106-1152.zip](https://github.com/terrymacdonald/DisplayMagician/files/9946466/DisplayMagician-Support-20221106-1152.zip)

**Enviroment (please complete the following information):**
 - Windows 10
 - DisplayMagician 2.4.1.14
 - Video Card: Asus NVIDIA 3080 Tuf
 - Number and make/model of monitors: LG OLED48C1AUB.AUS, LG OLED77CXPUA, Dell U2414H
 - Date of last video driver update: 10/27/22
 - Date of last windows update: 10/28/22

**Comment by terrymacdonald** [comment]
Hi,

I've looked through the logs you sent, and DisplayMagician appears to work
correctly in the last four runs that you performed before generating the
Support ZIP File. I also checked the Display Profiles, and your Home
Theater profile is correctly set to 3840x2160x60.000Hz :

                "Extra": {
>                     "Flags": 524288,
>                     "RefreshRate": 60,
>                     "FrequencyInMillihertz": 60000,
>                     "VerticalAspect": 900,
>                     "HorizontalAspect": 1600,
>                     "HorizontalPixelRepetition": 1,
>                     "TimingStandard": 406849793,
>                     "Name": "EDID-Detailed:3840x2160x60.000Hz"
>                   }


I did notice that your HDMI connection appears to go through from your
NVIDIA RTX 3080 to a Denon AVR system. This potentially could be part of
the problem. I've had a few people where their AV receiver caused an issue
for them. You could try to bypass your Denon AVR system and go directly to
your LG TV and see if the problem disappears?

Another thing that causes issues like this is having very long HDMI cables.
How long are your cables? Are they over 4m in length? You could move the TV
closer to your PC and then try to use it with a short cable and see if the
problem disappears. You should be able to eliminate both the Denon AVR unit
and the cable length with a bit of testing.

If you are still having issues even after the testing I;ve suggested above,
then it's more likely that your LG TV itself is at fault here. I have known
some TV's to not always set themselves correctly when receiving resolution
commands. Monitor's seem to be more reliable, but even that's not always
true of TV's. I'd try and see if there are any firmware updates for your LG
TV.

It is possible even a NVIDIA Driver or Windows Display Settings issue, but
that is far less likely. In any case it is highly unlikely to be a
DisplayMagician problem. DisplayMagician makes use of the NVIDIA, AMD and
Windows API calls, so intermittent problems are generally a hardware or
driver issue. If something reliably breaks and is repeatable then it could
be a DisplayMagician problem, but intermittent issues are 99% hardware or
driver issues.

Hope that help clarify a little bit, and please drop a note back here after
you've done some of the testing I've suggested above.

Thanks
*Terry*

**Comment by GibbousWaximus** [comment]
Hi Terry, thanks for your attention on this and also for the amazing software.
To clarify, the issue I'm seeing is when switching to my "Main" profile. The target resolution is the PC resolution 4k@120, but sometimes what gets set is the TV resolution 4k@60. I haven't looked at the contents of the support file, but I'll look through what's in there and see if I can find the example of the issue that occurred yesterday.

**Comment by GibbousWaximus** [comment]
I'm willing to accept that this might just be an nvidia issue, or an LG issue I can't do anything about, but I also want to clarify that the issue is not with the display you focused on. I have two LG TV's connected. One is the "Hometheater" connection and that goes through the Denon AVR, that display is not the issue. 

The display at issue is the _other_ LG TV and it has a direct connection from the video card to the TV with a short, high quality cable. 
From the config, this is the relevant display:
"DisplayId": 2147881089,
              "Details": {
                "Version": 65664,
                "Rotation": 0,
                "Scaling": 6,
                "RefreshRateInMillihertz": 120000,
                "Flags": 0,
                "ConnectorType": 97,
                "TvFormat": 556,
                "TimingOverride": 0,
                "Timing": {
                  "HVisible": 3840,
                  "HBorder": 0,
                  "HFrontPorch": 176,
                  "HSyncWidth": 88,
                  "HTotal": 4400,
                  "HSyncPol": 0,
                  "VVisible": 2160,
                  "VBorder": 0,
                  "VFrontPorch": 8,
                  "VSyncWidth": 10,
                  "VTotal": 2250,
                  "VSyncPol": 0,
                  "ScanMode": 0,
                  "Pclk": 118800,
                  "Extra": {
                    "Flags": 0,
                    "RefreshRate": 120,
                    "FrequencyInMillihertz": 120000,
                    "VerticalAspect": 9,
                    "HorizontalAspect": 16,
                    "HorizontalPixelRepetition": 1,
                    "TimingStandard": 494931318,
                    "Name": "CTA-861G:#118: 3840x2160x119.880Hz/P"
                  }
                }
I'll see if I can induce the issue and if I think I have something new to add I'll update this ticket.
Thanks!

**Comment by terrymacdonald** [comment]
Oh sorry, I completely missed that in the email as you rightly pointed out!

Thanks
Terry

**Comment by terrymacdonald** [comment]
@GibbousWaximus,

Just checking in to see if you've still been having the problem with your "Main" profile, and if you have whether you've been able to figure out a pattern for when it occurs? I'm kinda at a loss for what to test next to be honest after re-reading this issue, so I'm really hoping that it's either righted itself with a display driver update, or that you've noticed a pattern that we can use to figure out some other tests....

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @GibbousWaximus,

I'll close this issue for now but please reopen this issue of you start experiencing the same issue again. I'm hoping that you'll be able to discover another interesting bit of information if it fits happen again that will let us unlock what is going on here, but for now I'll close this issue so that I know where I'm up to trusting the rest of the open issues.

Please return this issue if you have the same problem again, or create a new issuer if you get a different problem.

Thanks
Terry
