### ISSUE TITLE
Unable to launch application

### ISSUE THREAD

**Issue by JSchoonbrood** [terrymacdonald/DisplayMagician#16]
**Describe the bug**
Throwing an exception on launch. 
"The type initializer for 'DisplayMagicianShared.ProfileRepository' threw an exception."
I've reproduced the bug on both the latest version (v1.0.6) and v1.0.5

**To Reproduce**
Start the application from start menu, the application will not start and just produce an error. 

I can bypass this starting issue by right clicking on desktop, going to create new profile which opens the app, but displays the error in more detail, clicking continue will take me to the application, but the application becomes unusable.

**Expected behaviour**
The application to launch successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/27826585/118571213-6a745e80-b775-11eb-87c2-1f1eb26f241b.png)

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for 'DisplayMagicianShared.ProfileRepository' threw an exception. ---> WindowsDisplayAPI.Exceptions.InvalidEDIDInformation: EDID does not contain necessary information.
   at WindowsDisplayAPI.DisplayConfig.PathDisplayTarget.get_EDIDManufactureId()
   at WindowsDisplayAPI.DisplayConfig.PathDisplayTarget.get_EDIDManufactureCode()
   at DisplayMagicianShared.NVIDIA.SurroundTopology.FromPathTargetInfo(PathTargetInfo pathTargetInfo) in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\NVIDIA\SurroundTopology.cs:line 56
   at DisplayMagicianShared.Topology.PathTarget..ctor(PathTargetInfo targetInfo, SurroundTopology surround) in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\Topology\PathTarget.cs:line 37
   at DisplayMagicianShared.Topology.Path.<>c.<.ctor>b__0_0(PathTargetInfo targetDisplay) in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\Topology\Path.cs:line 20
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DisplayMagicianShared.Topology.Path..ctor(PathInfo pathInfo) in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\Topology\Path.cs:line 20
   at DisplayMagicianShared.ProfileRepository.<>c.<UpdateActiveProfile>b__33_0(PathInfo info) in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\ProfileRepository.cs:line 542
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DisplayMagicianShared.ProfileRepository.UpdateActiveProfile() in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\ProfileRepository.cs:line 539
   at DisplayMagicianShared.ProfileRepository.LoadProfiles() in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\ProfileRepository.cs:line 670
   at DisplayMagicianShared.ProfileRepository..cctor() in H:\vscode-projects\DisplayMagician\DisplayMagicianShared\ProfileRepository.cs:line 80
   --- End of inner exception stack trace ---
   at DisplayMagicianShared.ProfileRepository.IsPossibleRefresh()
   at DisplayMagician.UIForms.DisplayProfileForm.DisplayProfileForm_Load(Object sender, EventArgs e) in H:\vscode-projects\DisplayMagician\DisplayMagician\UIForms\DisplayProfileForm.cs:line 241
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DisplayMagician
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Program%20Files/DisplayMagician/DisplayMagician.exe
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.8.12686
    CodeBase: file:///C:/Program%20Files/DisplayMagician/NLog.DLL
----------------------------------------
DisplayMagician.Shared
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Program%20Files/DisplayMagician/DisplayMagician.Shared.DLL
----------------------------------------
McMaster.Extensions.CommandLineUtils
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0.0
    CodeBase: file:///C:/Program%20Files/DisplayMagician/McMaster.Extensions.CommandLineUtils.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Windows.UI
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.UI.winmd
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files/DisplayMagician/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
ValveKeyValue
    Assembly Version: 0.3.1.152
    Win32 Version: 0.3.1.152
    CodeBase: file:///C:/Program%20Files/DisplayMagician/ValveKeyValue.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
ImageListView
    Assembly Version: 13.8.2.0
    Win32 Version: 13.8.2.0
    CodeBase: file:///C:/Program%20Files/DisplayMagician/ImageListView.DLL
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Win32 Version: 0.8.1.100
    CodeBase: file:///C:/Program%20Files/DisplayMagician/NvAPIWrapper.DLL
----------------------------------------
WindowsDisplayAPI
    Assembly Version: 1.3.0.13
    Win32 Version: 1.3.0.13
    CodeBase: file:///C:/Program%20Files/DisplayMagician/WindowsDisplayAPI.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Reporting Logs**
[LogReporter.20210518.010032.log](https://github.com/terrymacdonald/DisplayMagician/files/6497488/LogReporter.20210518.010032.log)

**Comment by terrymacdonald** [comment]
Hi @JSchoonbrood,

Thanks for logging the issue so I can make DisplayMagician better! It looks from the error you posted that DisplayMagician can't get the EDID information from one of the monitors connected to your computer. The EDID information allows DisplayMagician to identify the display connected to it, and that in turn allows us to track when a Display Profile is available to use.

Was this working in the past? Or has it always been broken?

Did you recently add a new monitor to your computer? Or did you recently upgrade your display driver? Or did you update Windows 10? 

To be honest, I'm not sure if I'll actually be able to fix this, other than turning the error into a nicer warning.....but we'll at least give it a go.

One thing you'll need to do first is to set DisplayMagician into 'Trace' mode, and then create a trace DisplayMagician.log file that will help provide me with more information.  You can do this like this:

- Open the DisplayMagician settings file called Settings_1.0.json that is in C:\Users\<username>\AppData\Local\DisplayMagician folder with notepad.
- Change the LogLevel line to Trace e.g. "LogLevel": "Trace",
- Save the file. 
- Restart DisplayMagician.

DiaplyMagician will generate a trace level DisplayMagician.log file that you'll find in C:\Users\<username>\AppData\Local\DisplayMagician\Logs folder. The Trace log file will give me a lot of information that I can then use to troubleshoot this issue deeper.

Please reply to this issue to answer the questions I raised above, and attach the DsiplayMagician.log file to your reply. It will hopefully let me figure out what information your display is missing.

Thanks
Terry

**Comment by JSchoonbrood** [comment]
Hi,
Thanks for the response. I currently have a 3 monitor setup. I've always found that one of the monitors has a weird behaviour and is sometimes not detected, so I typically use the windows shortcut (WinKey + Ctrl + Shift + B) to restart the graphics drivers which solves the problem.

The problem monitor is the same brand and model as one of the other monitors, it's a bit weird how it's lost it's EDID information (which seems to be the problem, I doubt there is an easy fix short of rewriting it manually as a quick search doesn't show only helpful tools)

Now that you've brought it up, by disconnecting this "problem" monitor, I am able to view my other two monitors in the software. 

I've only just found out about the software, so this is my first experience with it.

I found the software did not work, and I opted to blame this firstly on Windows 10 as that's usually where all my problems start. So I reset windows 10 to a fresh install, with fresh graphics card drivers and the problem was still present.

Attached is the trace file requested. Hopefully it may help, but I won't get my hopes up and may source a new monitor if that is the issue.
[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/6507126/DisplayMagician.log)

Thanks for your time.

**Comment by terrymacdonald** [comment]
Hey no problems @JSchoonbrood. I'm happy to help. 

I've spent some time tonight looking at the code in that area, and it's not very robust, so I've taken the opportunity to try to make it more robust, as well as report more information about what is happening in that part of the codebase into the trace file. It should hopefully help me troubleshooting things better when I get a similar error to what you experienced.

Thank you for the DisplayMagician.log file. It confirms that one of the monitors responded with some EDID information but it wasn't in an invalid format. There isn't anything I can do in DisplayMagician to work around that I'm afraid, sorry.

I'll try to add some code to report which device has issues in the log file over the next few days which will hopefully help others when they experience a similar problem. I'll release that in DisplayMagician v1.1.0 which I'll drop later this week.

It's got some cool features like being able to run a shortcut using a Windows Hotkey combination, and the ability to start more than 4 start programs before you run the main application/game. Hopefully that makes things even a little easier for everyone to use DisplayMagician!

Good luck, and I'll close this issue as 'can't fix' (though I will add some code to report EDID errors better).

**Comment by JSchoonbrood** [comment]
Thanks Terry,

With the information you've provided, I've explored the problem on my end a bit more. I've extracted EDID dumps of both monitors using i2c tools to find they both dump different EDID information (which is expected) and the checksums add up.

Both the monitors that seem to be having issues with this software have valid EDID info.

Is there any more details that you could perhaps dig up that may help solve this problem?

I also pulled the Windows EDID info from the registry for both monitors to find out that windows think they have the same EDID which is rather interesting as the dumps show different valid EDID info.

Cheers

**Comment by JSchoonbrood** [comment]
Just a quick update, tried the latest version just released and all of a sudden its kind of working!

![image](https://user-images.githubusercontent.com/27826585/119134078-9a9d5500-ba34-11eb-8a20-2fa164136bb3.png)

The two monitors on screen are the ones that seem to be having issues with each other, they are both of the same brand and I would assume they both would say VG2401 Series, but regardless, it works. I haven't modified anything yet either. Will give it some time to see if anything emerges, but seems promising.
