### ISSUE TITLE
Run program as Multiple Users on same PC

### ISSUE THREAD

**Issue by JoetheShow20** [terrymacdonald/DisplayMagician#166]
We have a few different people signing into the same racing rig at home. If one userA doesn't log out, the next user(userB) won't have Display Magician available unless the restart the PC to log that other userA out.

Is it possible to have Display Magician run by multiple users on the same PC?

I realize this could be solved by the user simply logging out, but sometimes with kids, it's not that simple.

Great product! Love the solution!

**Comment by terrymacdonald** [comment]
Hi @JoetheShow20,

Sorry for the delay getting back to you. 

Unfortunately DisplayMagician was designed to only have one copy running across the entire PC. I designed it that way as there are a lot of issues caused when two different software components try to use the NVIDIA/AMD/Windows display libraries at the same time. It avoided a LOT of problems by heading own that design path.

This design unfortunately means that  I wouldn't be able to support having two users running DisplayMagician at the same time.

Sorry!

Terry
