### ISSUE TITLE
Display Magician won't open if using Steam Beta

### ISSUE THREAD

**Issue by CuteRogue** [terrymacdonald/DisplayMagician#173]
**Describe the bug**
Display Magician can be opened normally when using steam, but when I opt-in for Steam Beta (I did it for new Big Picture Mode) it suddenly crashes and can't be opened again.
I tried to reset my steam back to standard version then it can be opened again. I attached the log when the problem happens, I already checked a bit and it might be the steam i hope it helps

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Steam
2. Open Account Setting in Steam on Steam/Setting/Account
3. Change Beta Participation to Steam Beta Updates
4. Steam will download new Beta Updates and restart
5. When process completed open Display Magician
6. Display Magician will start and instantly closed
7. Turn Beta Participation back to "opt-out for all beta" then Display Magician will normally start

**Expected behaviour**
Display Magician should be able to start even with Steam Beta Updates installed without error

**Reporting Logs**
- [DisplayMagician1.log](https://gist.github.com/CuteRogue/0ac12e889e741bd12bca6b99c1606160)
- [DisplayProfiles_2.4.json](https://gist.github.com/CuteRogue/e1335093d3927257a1f821e6518d4de7)  
- [Settings_2.4.json](https://gist.github.com/CuteRogue/4d365d2aa6b22183cde8036bef573c1b)
- I don't use shortcut so it doesn't have Shortcut Json files

**Enviroment (please complete the following information):**
 - Windows Version: Win 10
 - DisplayMagician Version: 2.4.1
 - Video Card: R9 Fury
 - Number and make/model of monitors: LG 25UM57, LG 20MP38HQ, Coocaa 32TB1000 (this one is a TV)
 - Date of last video driver update: 2022-10-05 (Nimez Driver)
 - Date of last windows update: ‎2022-12-08

**Additional context**

**Comment by terrymacdonald** [comment]
Oh interesting! Looks like the new steam client uses a completely new file
format. This might be quite difficult to support until some of the upstream
libraries I use start supporting the new file format.

I'll have a play with the new steam client over the next few weeks and see
if I can sort something out. I was hoping to do a bit of DisplayMagician
work over the holiday period as I've not had much time to work on it
previously unfortunately.

It may take a little while to figure it out. I'll also see if I can make
that code more robust so it doesn't crash when a new file system is
released.

Thanks
Terry

**Comment by CuteRogue** [comment]
Great! Thanks!
I'll be looking forward for it. In mean time i just switch back to non-beta since I need DisplayMagician more than Steam Beta

**Comment by terrymacdonald** [comment]
@CuteRogue Some bad news! The Valve file parsing library I use for parsing Steam library files has been updated to the latest version, but it doesn't support the .net Framework v4.8, which is what DisplayMagician uses for it's framework. What this means is that I cannot use the new Valve file parsing library unless I move DisplayMagician to .net6... and that is a MAJOR project (as in potentially months of work).

I was always going to have to move to .net6 at some point, but it will take a bit of time to get this done. Really sorry to be the bearer of bad news, but it is what it is.

I have integrated that reliability fix I mentioned earlier though, so at least DM won't crash if people are using Steam Beta.

I will update the README documentation to highlight that DM won't support the Steam Beta client until that work happens.

Thanks
Terry

**Comment by CuteRogue** [comment]
oh that's too bad.. its ok though
thanks for the information.. looking forward for next major update then XD

**Comment by terrymacdonald** [comment]
@CuteRogue I've been doing some testing, and I think I've managed to work around that problem. I am using Steam Beta and it works on my system. Could you please download and install this test version of DisplayMagician and see if it works with Steam Beta? If you have errors please ensure that your DM logging level is set to 'TRACE' from within the Settings page, and then see if you can cause the  issue, then send me another Support ZIP File. 

[DisplayMagicianSetup-v2.5.0.331.zip](https://github.com/terrymacdonald/DisplayMagician/files/10235613/DisplayMagicianSetup-v2.5.0.331.zip)

This version of DisplayMagician adds quite a few new features (e.g. a built in FOV calculator for if you are a simracer) and hopefully works fine. If you could install  and give it a test I'd really appreciate it!

Thanks
Terry

**Comment by CuteRogue** [comment]
That was fast man.. @terrymacdonald 
I've tested it and it works with Steam Beta Updates without any issues so far (been 3 hours just playing with Big Picture Mode).
Thanks a bunch for taking your time to work on my issue!

and for that FOV calculator, I'm not a hardcore simracer and unfortunately my steering wheel is broken about 6 months ago so I can't actually test it if its good or not (I also don't understand what I need to set up with values from that calculator), sorry..

**Comment by terrymacdonald** [comment]
No problems. Thanks for testing the rest! I might release that to my beta testers if its working well. It helps me a lot having people other than myself to test, so I can't thank you enough!

I'll close this issue for now. Feel free to reopen it if you still have problems, or open a new issue if you find something different that I've broken :D.

Thanks
Terry
