### ISSUE TITLE
"Choose what happens before" issue

### ISSUE THREAD

**Issue by stringfieldmark** [terrymacdonald/DisplayMagician#18]
**Describe the bug**
I have programs set to run before the launch of a game. All have the "Don't start if program already running" checkbox checked (enabked).

If none of the programs are currently running, all programs start as expected prior to game launch.

However, if the program is already running, all programs below the running program will not start. The game does launch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set SimHub as first program to start
2. Don't pass any arguments
3. Enable the "Don't start if program already running" checkbox
4. Set CrewChief as second program to start
5.  Don't pass any arguments
6. Enable the "Don't start if program already running" checkbox
7. Save profile to desktop
8. Manually start SimHub
9. Once SimHub is running launch the game from the DisplayMagician game shortcut on the desktop 

**Expected behaviour**
SimHub should be, and is, skipped as already running but CrewChief should start with the the game following after.

**Screenshots**
If necessary, let me know what screenshots would be helpful 

**Reporting Logs**
If required I can add. Let me know if they are needed.

**Enviroment (please complete the following information):**
 - Windows Version: 20H2 (19042.985)
 - DisplayMagician Version: 1.1 1
 - Video Card: Asus NVIDIA GTX1080ti OC
 - Number and make/model of monitors: 3xMSI MAG322CQR and 1xBenQ PD3200U (running at 1440)
 - Video driver version: 446.47
 - Date of last video driver update: [e.g. 2021-05-18]
 - Date of last windows update: [e.g. 2021-05]

**Additional context**
This was noticed purely by accident as I normally always ensure any programs set to run are closed. So, I am unsure in what version this issue may have started or if was always present.

**Comment by terrymacdonald** [comment]
Thanks @stringfieldmark . I've been away for the last few days but will take a look at this in the next day or two. I'm wondering if some of the recent changes I made for unlimited program starts had an effect on this, as it was working back when I built that functionality in. It's possible I missed copying a setting across or something like that.  I'll take a look and check.

By the way, thank you for an excellent bug report. It's very clear to me now the area of the codebase I need to look at, so your clear report really helps. I'm going to make it an example of a 'good first issue'!

Thanks
Terry

**Comment by terrymacdonald** [comment]
Ok. I've fixed that issue in develop branch, but will be rolling that out in v1.1.2 which will be about 3 weeks away. The reason for this is that I've been rolling out so may fixes that I think people will be getting annoyed with the number of times they need to update. I'm trying to make it 2-3 weeks between releases now, and to roll a few more features into each release.

Another edge case I found is that some start programs spawn different processes from the one that we started, and that means that I needed to figure out a way to discern this. I've done so now, so it should even close the children of the parent process if its a direct launcher. I haven't yet written logic to walk the process tree to individually close each process as that seems a tad excessive at this point. I'll wait for more feedback from the userbase before heading down that path.

**Comment by stringfieldmark** [comment]
NP Terry. Hope you had a well deserved break.

Pleased you were able to find the issue and makes sense to not over whelm
with regular updates.

At the mo I just make sure all apps are closed before starting up (although
I am forgetful and one gets missed every now and then).

Happy to continue testing as new releases come through. This app has made
things so much easier for me and I can even, just, make a cuppa while
waiting for the app to do its thing.

Keep up the gr8 work and I look forward to the next release.

Cheers,

Mark

**Comment by terrymacdonald** [comment]
@stringfieldmark The fix for your issue you submitted is in DisplayMagician v1.1.2 I released today. 

I've also added GOG.com launcher support, and Epic Games launcher support because it turned out they were pretty easy to develop :).
