### ISSUE TITLE
Program won't let me create Display Profiles

### ISSUE THREAD

**Issue by ianharbs** [terrymacdonald/DisplayMagician#184]
Everytime I open the program this screen shows up.
I tried uninstalling Helios Display Management, and reinstall Display Magician, but nothing worked so far.

Does anyone know how to solve this?
![image](https://user-images.githubusercontent.com/121392113/212475749-e26cd169-30b8-45b4-950f-94444367b7de.png)

**Comment by ianharbs** [comment]
Nevermind, just got it.
I just right-click to desktop and create a new display profile under DisplayMagician

![image](https://user-images.githubusercontent.com/121392113/212476019-46809b21-a20d-4f60-8d50-95b1ad198b84.png)

**Comment by terrymacdonald** [comment]
Hi Ian,

Actually, there is a small Close button at the bottom right. Press that and
the message will go away and shouldn't come back. I sometimes add upgrade
messages that describe the functionality that was just added in the upgrade.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @ianharbs Actually looking at this again I wonder if there is a logic error in DisplayMagician for new users who don't have any profiles. I'll take a look and see and I'll create a new issue to rectify it if I find something wrong.

Thanks for reporting this!
Terry

**Comment by terrymacdonald** [comment]
@ianharbs I did find an issue for new users, where the default setting is now is to minimise DisplayMagician to the System Tray/Notification area. This isn't very obvious, so I'll have to change the default, and update the instructions to point this out.

Thanks again for bringing this to my attention.
Terry
