### ISSUE TITLE
DisplayMagician won't load anymore.

### ISSUE THREAD

**Issue by ArcticGypsy** [terrymacdonald/DisplayMagician#214]
When I go to open DisplayMagician 2.5 (Latest), I get the initial splashscreen, saying that the app is loading and it may take a while depending on number of games installed, but when it close the application has not loaded, it briefly appears in task manager but then disappears. There is nothing in the taskbar icons. It does not shaw any errors.

**Reporting Logs**

If DisplayMagician does not:

[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/11103114/DisplayMagician.log)

**Enviroment (please complete the following information):**
 - Windows Version: Windows 11 Home 22H2 22621.1413
 - DisplayMagician Version 2.5
 - Video Card: RTX 3080 TI
 - Number and make/model of monitors: 6 Monitors (4 on my rig and 2 on my desk)

**Comment by ArcticGypsy** [comment]
I reinstalled windows and it works again.

**Comment by terrymacdonald** [comment]
Thanks @ArticGypsy. Good to hear you got a solution. Feel free to log
another issue of you experience any more problems.

Thanks
Terry
