### ISSUE TITLE
Creating a game shortcut without referencing a game produces an unhandled exception

### ISSUE THREAD

**Issue by ngoetje** [terrymacdonald/DisplayMagician#25]
Unhandled exception as soon as the game shortcuts area is selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'game shortcuts'
2. Click on 'new'
3. Select any monitor configuration
4. Choose "game to start": Don't start a game
5. Enter any name (e.g. "asdf")
6. Click on "Save"

**Expected behaviour**
A new game shortcut is added to the library.

**Reporting Logs**
 System.NullReferenceException
  HResult=0x80004003
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=DisplayMagician
  StackTrace:
   at DisplayMagician.UIForms.ShortcutILVRenderer.DrawItem(Graphics g, ImageListViewItem item, ItemState state, Rectangle bounds) in F:\_Git_Repos\_private\DisplayMagician\DisplayMagician\UIForms\ImageListViewRenderers.cs:line 101

**Enviroment (please complete the following information):**
 - Windows Version:Win10
 - DisplayMagician Version 1.1.4.0
 - Video Card: GTX2060 super
 
**Additional Info**
I already debugged the error and it seems the whole system is broken if there is no game referenced from which an icon can be created.

**Comment by terrymacdonald** [comment]
I'll have to triage this in order to roll a fix into DisplayMagician v2.0.0. I'm afraid a current ETA is just under 2 months from now, but I'll have to see how I go.

Thank you for reporting this issue though. I'm working to make DisplayMagician nice and robust, and these sorts of things help a lot!

Thanks
Terry

**Comment by terrymacdonald** [comment]
From what I can tell, it's likely that the actual Shortcut editing form is letting a Shortcut get created when it shouldn't. I'll triage a bit closer once I've finished the AMD Eyefinity video library which is my main focus at the moment.

**Comment by ngoetje** [comment]
Thanks for looking into it. Yesterday I just copied the "ShortcutBitmap" data from another shortcut to a new one and then there is no exception.

**Comment by terrymacdonald** [comment]
Just spent some time looking at this again, and it is definitely a problem. I completely missed putting in logic for this situation! Quite embarrassing.  I'll figure out a solution shortly for this. 

As the DisplayProfile logic rewrite for v2.0.0 is taking so long, and I'm getting a short list of bugs, I'm now thinking I'll actually release a v1.1.5 to fix some of these annoying bugs to get them out of the way.

**Comment by terrymacdonald** [comment]
Have coded a fix, and it will be part of v1.1.5 release in a week or two. Closing as the fix is in place, just awaiting the next release.

**Comment by terrymacdonald** [comment]
@ngoetje I'd appreciate it if you could test the attached release to make sure that it fixes the 'No Game' shortcut issue you reported. This test install can simply be unzipped and installed over your existing DisplayMagician install.

Please report back whether or not the 'No Game' shortcut now works for you. Based on your feedback I'll craft a new official release.

Thanks
Terry

[DisplayMagicianSetup-v1.2.0-test.zip](https://github.com/terrymacdonald/DisplayMagician/files/6876773/DisplayMagicianSetup-v1.2.0-test.zip)

**Comment by ngoetje** [comment]
Sorry been away on vacation for the last weeks. Fix has been successfully tested, thanks!

**Comment by terrymacdonald** [comment]
Great! Ok, one thing to remember. When the official v1.2.0 is released, you will need to uninstall the test version I just gave you, so that v1.2.0 will install correctly. The reason is that they both have the same version number, and the installer prevents a dual installation.

Thanks for testing!
Terry
