### ISSUE TITLE
Add posibility to turn off applications when profile is loading

### ISSUE THREAD

**Issue by fifowole** [terrymacdonald/DisplayMagician#304]
**- Describe the solution you'd like**

Would be great to have possibility to select applications to be turned off when profile is loading.
It could be under "Configure Game Shortcut" as part of "Choose what happens before", where you could select between "Start this program" and "End this program"
For example when I'm starting iRacing, I don't need Steam, Epic, Dropbox and MS OneDrive and Teams to run..

**Comment by terrymacdonald** [comment]
Hi @fifowole,

You can do that already using the existing mechanisms. Simply add the
'taskkill' into the 'Start this program' field, and add '/im
<nameofapp>.exe' to the 'Pass arguments to program' field. You also need to
untick the 'Close started program when finished' checkbox.

I've tested it myself. Here is an example that kills notepad.exe when you
start your game. Just change your exe name to the program you want to stop.
e.g. '/im msteams.exe'

[image: image.png]

I'll have a little think about if I could add this without complicating
things too much for users. It might be a difficult thing to add and still
be simple to use.

Thanks
*Terry*

**Comment by fifowole** [comment]
Hi Terry,
awesome ! 
Didn't come on my mind to use it this way. 
Thank you for info and keep up the good work ;)

**Comment by fifowole** [comment]
Solved by using "taskkill /im appname.exe" command
