### ISSUE TITLE
Steam library not recognised anymore

### ISSUE THREAD

**Issue by fifowole** [terrymacdonald/DisplayMagician#329]
Suddenly DM won't see the Steam library. Like 2 days it was still OK

I'm not using any Steam Beta program.
My disk drive with Steam installed didn't change.
I don't see Steam game.
I can only see Epic library games when editing or tryiing to add new game shortcut:
![image](https://github.com/user-attachments/assets/61d8fed8-7e9a-4d98-a9f1-f616afa87a22)

**Screenshots**
![image](https://github.com/user-attachments/assets/0ea2478d-9579-4552-9880-7e6e2b0347e8)

**Reporting Logs**
[DisplayMagician-Support-20240914-1759.zip](https://github.com/user-attachments/files/17003018/DisplayMagician-Support-20240914-1759.zip)

**Comment by terrymacdonald** [comment]
It's likely the stream client was updated and the new version is live. Do
you know if your stream client updated recently?

**Comment by KevinNeb** [comment]
I'm having the same issue, and it would seem like the Steam client was just updated.  Now what?

<img width="366" alt="2024-09-15 11_49_45-About Steam" src="https://github.com/user-attachments/assets/ca74b48a-94af-48b0-a208-1a741f8cce33">

**Comment by Manfredk2** [comment]
same here. My racing games RF2, AMS2 and Raceroom are no longer visible.

Steam client (no beta) was updated two or three days ago

**Comment by terrymacdonald** [comment]
Hi all,

There is a new version of DisplayMagician under development, but it's not
quite ready yet. It is a major internal update from .net framework 4.8 to
.net 8.0 core. This is a big change, and it will cause bugs. There are
still errors that I'm trying to fix.

A big problem is that I cannot simply update v2.5.0 to handle the new steam
client file format. The library I use to read the file format only worked
with .net core, which forced the upgrade, and all the huge amounts of work
that went after that.

So we're a little stuck right now. DM V2.7.0 isn't quite ready for release,
and DM v2.5.0 didn't work with stream library directly (you can always add
the game exes directly as applications though).

I'm working as far as I can to get an alpha build out for testing, but
there are 4 tricky last errors I have to fix for that.

I'll drop a link to the alpha build in this issue when I need some initial
testing done.

Thanks
Terry

**Comment by gosusnp** [comment]
Happy to help or test anything. good luck with the fix.

**Comment by Manfredk2** [comment]
Take your time. Display magician is a wonderful and very helpful tool

**Comment by fifowole** [comment]
Yep no rush, we are happy to help wherever you need.

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry

**Comment by gosusnp** [comment]
@terrymacdonald, listing selecting steam apps worked for me. Thanks for the fix!

**Comment by terrymacdonald** [comment]
Excellent news! I'll close this issue, and you can keep an eye out for the full release of DM v2.7 when we finish testing.

**Comment by fifowole** [comment]
Just to confirm STEAM library is back for me after upgrade to 2.7.0 beta. Great job Terry !

**Comment by KevinNeb** [comment]
I've also used it 4-5 times now with no issues.  All good and no bugs that I can see.  Great job @terrymacdonald Terry.
