### ISSUE TITLE
DisplayMagician v2.7.0-alpha.1 installer

### ISSUE THREAD

**Issue by gosusnp** [terrymacdonald/DisplayMagician#335]
**Describe the bug**
The DisplayMagician shortcut after the install opens explorer on root rather than starting displaymagician.
Launching the exe directly from the install dir worked.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 2.7.0-alpha1
2. Start Menu > DisplayMagician
3. See that explorer opened up

**Expected behaviour**
Starting display magician instead of explorer

**Enviroment (please complete the following information):**
 - Windows Version: [e.g. Win11]
 - DisplayMagician Version [e.g. 2.7.0-alpha1]

**Comment by terrymacdonald** [comment]
Hmmm! Thanks for raising this @gosusnp. I've not seen a similar error so far. 

Based on what you are describing, the Start Menu entry may be incorrect. I wonder if the previous DisplayMagician Start Menu item wasn't properly uninstalled? It might be pointing to the old file.

Can you please see if you can start DisplayMagician directly? Can you please open windows explorer and navigate to:

`C:\Program Files\DisplayMagician`

and then run the DisplayMagician.exe?

What happens then?

**Comment by gosusnp** [comment]
Launching DisplayMagician directly works fine. It launched the app in the tray. I can open it from there as usual.

I see the new shortcut created in `Start Menu/Programs` is missing a target. Not sure about the uninstall, I don't see anything that seems to be left over.
Looking at the Created/Modified dates of the shortcut, they also look fresh, timestamps match the install.
![Screenshot 2024-10-03 151815](https://github.com/user-attachments/assets/8c8ba0a2-c3a8-4d29-8fb9-b016cfe4a060)

**Comment by terrymacdonald** [comment]
Hmmmm. That helps thanks. It looks like the installer needs some care and
attention. I'll have a look to try and guess why, but I might need to ask
you some questions about you system to see if there is something different.

Actually, can you tell me what language your Win11 system is in? It's it
en-US, out something else?

Thanks
Terry

**Comment by gosusnp** [comment]
Sure, I have Win 11 Pro, Version 23H2, Build 22631.4169.
Main language is `en-US`. There is French but as secondary, checking the drive, I see `C:\Program Files (x86)` and `C:\Program Files`
Standard for the most part is it is mostly a gaming station, I may have installed WSL at some point but that shouldn't really affect anything.

I got the prompt to go through accepting an unsigned app, not sure if there's anything related to that.

**Comment by fifowole** [comment]
Confirming this issue on mine PC. 
Win 11 Pro
Build: 22631.4317

**Comment by terrymacdonald** [comment]
This one is odd. I'm trying to swap over to using an "advertised" shortcut for the next beta version, to see if that stops this issue occurring. Having some trouble getting it to work.

I really don't know what part is stopping this from working in it's current shortcut form as it is working on all test machines I have here. I was using an advertised shortcut in the past, but the same code from the older DM installer doesn't work in the new v4 setup project I have. 

I shall have to do a bit more troubleshooting. 

It seems like this is the only real issue I have left to solve, which is great considering how much of the codebase had to change! 

Thanks
Terry

**Comment by terrymacdonald** [comment]
@gosusnp @fifowole Can you please test this new beta version? It should be working now as I've managed to get the advertised shortcut to work, so it should just work :)

https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.1-beta.9

As always please report if this fixes the shortcut issue. If you find something else broken, please log a new issue so I can track it seperately.

Thanks!
Terry

**Comment by gosusnp** [comment]
@terrymacdonald , thanks for the fix, I am traveling at the moment. I'll try it out when I come back.

**Comment by gosusnp** [comment]
@terrymacdonald, the process was a bit weird. I am ran into different issues with the installer itself this time.

It failed to uninstall the previous version (I still had 2.7.0-alpha.1), when attempting to close the app, failed to do so, however, still tried to install and ended up failing. After that failed attempt, it was only trying to repair and failing to repair. Even if I made sure the app was closed.

Then I tried again to uninstall, install. The shortcut looks good this time.
I think we can close this one, let me know if you want to track my update issue, however, I don't think I have anything on my desktop to reproduce the issue.

**Comment by terrymacdonald** [comment]
Hi @gosusnp. I think your upgrade issues were due to the fact that it's upgrading the same version. Windows installer only tracks the first 3 digits of any upgrades, so updates to the build (the last digit) are treated as the same application. It would have most likely caused that issue.

**Comment by gosusnp** [comment]
I see, looks like others shouldn't run into this from now on.
