### ISSUE TITLE
Update screen appears despite being on the same version

### ISSUE THREAD

**Issue by Memememesxy** [terrymacdonald/DisplayMagician#338]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest beta
2. Open the app
3. Get the Pop up

**Expected behaviour**
No pop up occurs if you are on the latest version

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/10be7b95-052d-4f9d-8fdd-3bb441a07a86)

**Reporting Logs**
[DisplayMagician-Support-20241019-0013.zip](https://github.com/user-attachments/files/17441785/DisplayMagician-Support-20241019-0013.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Win 11 23H2
 - DisplayMagician Version: 2.7.1.9
 - Video Card: MSI NVIDIA 3070
 - Number and make/model of monitors: 1xLG TV SSCR2, 3x MSI G27C5
 - Date of last video driver update: [e.g. 2024-10-18]
 - Date of last windows update: 2024-07-16

**Additional context**
Get this prompt every time I open the app despite being on the version that it wants me to update. Using the skip button does not fix this like I would expect either. Remind me later seems to actually put a hold on the update window pop up.

**Comment by terrymacdonald** [comment]
Oh shoot! That is very weird. I will check that out when I get home.

**Comment by terrymacdonald** [comment]
I've just had a look at the autoupdater code, and it looks like it's
grabbing the current version from the old version location, which isn't
right any more, as I changed which version was the correct one. I'll have
to update the code and create a new release.

Terry

**Comment by Memememesxy** [comment]
Too easy, figured I would log it even if it is minor. Have a good one and cheers for the software, I use it basically daily to switch to my telly and back-------- Original message --------From: terrymacdonald ***@***.***> Date: 19/10/24  11:12  (GMT+10:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: Memememesxy ***@***.***>, Author ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] Update screen appears despite being on the same version (Issue #338) 
I've just had a look at the autoupdater code, and it looks like it's

grabbing the current version from the old version location, which isn't

right any more, as I changed which version was the correct one. I'll have

to update the code and create a new release.



Terry



On Sat, 19 Oct 2024, 1:37 pm Terry MacDonald, ***@***.***>

wrote:

**Comment by terrymacdonald** [comment]
@Memememesxy this should now show you an upgrade to v2.7.2.1. Please perform this upgrade, and *hopefully* the update screen should stop being a problem. Please report back what you find (good or bad).

**Comment by Memememesxy** [comment]
Seems too have worked. I did press the remind me in a week option though in the previous version while testing so i give you the cases it did it for. I will let you know if it happens again.If you do want any testing done while you are doing releases please feel free to reach out and I will see what if I can find any bugs as I go. Least I can do really!
-------- Original message --------From: terrymacdonald ***@***.***> Date: 19/10/24  20:15  (GMT+10:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: Memememesxy ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] Update screen appears despite being on the same version (Issue #338) 
@Memememesxy this should now show you an upgrade to v2.7.2.1. Please perform this upgrade, and hopefully the update screen should stop being a problem. Please report back what you find (good or bad).

**Comment by terrymacdonald** [comment]
Thanks!
