### ISSUE TITLE
Windows Background

### ISSUE THREAD

**Issue by neilpearson62** [terrymacdonald/DisplayMagician#36]
Would it be possible to add background support?

I like to switch between surround and Extended mode and Would like to setup backgrounds for each.

**Comment by terrymacdonald** [comment]
Hi @neilpearson62 ,

To be honest probably not, at least for the next year. I'm really trying to focus on getting the new display libraries I've created tested and integrated into DisplayMagician v2.0.0, and I have a list of features specifically related to improving the reliability of process detection and similar functionality.

I have already has this suggestion before, and I had a quick look to see how easy it would be to implement. At the time it was quite a bit of development time to do. 

At this stage I want to keep working on core functionality, so I'll keep this issue as a reminder, but it won't be anything I'll be implementing anytime soon.

Thanks for your suggestion though. I'm really happy to hear about any ideas people have. There have been so many great suggestions that have improved DisplayMagician in the past, so happy to hear anything else you would like to suggest. My only all is that you submit each one as a separate issue.

Thanks
Terry

**Comment by terrymacdonald** [comment]
So as you can tell, I did end up implementing this. It turned out to be a bit easier than I thought, though it did take me a day :).

I wasn't expecting to add this, but I go bored with doing the monotonous video library stuff every day. This was an interesting change! Here is a sneak peek of how it ended up:

![image](https://user-images.githubusercontent.com/5721772/132123346-8318fdfb-f011-4f99-a702-6eea3aece6fc.png)

It will allow you to choose a wallpaper, and how it will appear. Or if you want to clear the wallpaper so there is nothing. Or if you just want to leave the desktop wallpaper alone (default). You can also grab the existing desktop wallpaper from windows into the display profile to make it even easier.

Hope you like it! This feature will be released in DisplayMagician v2.0.0.

Thanks
Terry

**Comment by neilpearson62** [comment]
Oh this is awesome!

Thanks so much!   Can't wait to use it :)

**Comment by terrymacdonald** [comment]
I'm closing this issue as the code had been created and integrated into DisplayMagician v2.0.0. This feature will be part of the initial V2.0.0 release.

There is now a new 'Profile Settings' button on the display profile page that allows you to set up the windows background settings that you want to apply when the display profile is used.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@neilpearson62 Great news. I've got another DisplayMagican v2 build to test. This one has had a lot of local testing, and I've fixed a lot of bugs that I've found. And now I think it's ready for another round of testing. 

I'd really love it if you could test this out for me. To install DisplayMagician v2.0.0-alpha2:

- Firstly, uninstall DisplayMagician v2.0.0 alpha1 if you installed it earlier.
- Secondly, download and install DisplayMagician v2.0.0 alpha2 from this issue
- Thirdly, test it out :).

To set the Windows Background options you can now click on the new 'Profile Settings' button on the 'Display Profile' window. The Windows Background is set or cleared per profile, so if you want to swap backgrounds you'll need to set different backgrounds for each profile. Please test it out, and tell me what you think.

Hopefully it goes well for you and does everything it should, but if you do find any issues, please log them as new issues here: https://github.com/terrymacdonald/DisplayMagician/issues/new?assignees=terrymacdonald&labels=bug&template=bug_report.md&title=

Thanks 
Terry

[DisplayMagicianSetup-v2.0.0-alpha2.zip](https://github.com/terrymacdonald/DisplayMagician/files/7229458/DisplayMagicianSetup-v2.0.0-alpha2.zip)

**Comment by neilpearson62** [comment]
Hi Terry!

thanks for the alpha!

I ran it for the last 8 or so days and I did not come across any issues,
apart from when I installed it, I had to re-setup all my profiles.

I just installed WIN11 so ill let ya know if I come across anything with
that.

love the wallpaper changing!  killed it :D

Neil
