### ISSUE TITLE
HDMI audio devices can not be used / switched to 

### ISSUE THREAD

**Issue by gpo123** [terrymacdonald/DisplayMagician#39]
**Describe the bug**
In a profile I am using the monitor speakers. As they are driven via HDMI directly from the NVIDIA card these devices cann not be used with DisplayMagician 1.14  
**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new game profile
2. choose a HDMI audio device on tab 2 ( in my case the monitor with extension "(NVIDIA High Definition Audio)"
3. Save this profile. It will get a warning icon.
4. If you try to run the game shortcut via shortcut, you will get a warning saying that this device is not connected although it is.  

**Expected behaviour**
Changing the audio output to HDMI / monitor devices should also be possible

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9412171/133124621-96d6a9ae-3495-4976-9cd0-d18b31ad7f6b.png)

**Reporting Logs**
- Create a TRACE-level DisplayMagician.log file by running `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` in a command prompt.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Feel free to check the DisplayMagician.log file for any information you might not want to share with the public. 
- Once you're happy, attach the DisplayMagician.log TRACE file you just created to this issue.

**Enviroment (please complete the following information):**
 - Windows Version: Microsoft Windows [Version 10.0.19043.1165] 21H2
 - DisplayMagician Version; 1.1.4
 - Video Card: MSI Gaming X 1660 Super
 - Number and make/model of monitors: Dell U2312HM, AOC24G2W1G4, Iiyama PL3461WQ
 - Date of last video driver update: Nvid 471.96 Sept `21
 - Date of last windows update: Sept '21

**Additional context**
It seems that "audioDevice.State" always returns "unplugged" for HDMI devices. At least on my NVIDIA 1660 Super video card. So I compiled "ShortcutItem.cs" Line 1304  with the following change:
if ((audioDevice.State == DeviceState.Unplugged) && **(!audioDevice.FullName.Contains("NVIDIA") == true)**)

[DisplayMagician.error.log](https://github.com/terrymacdonald/DisplayMagician/files/7156137/DisplayMagician.error.log)

**Comment by terrymacdonald** [comment]
Those is likely to be a limitation from the upstream audio library that I used, but I'll have to do some more testing to be sure. I don't have any HDMI connected speakers at present so I'll have to do a little hunting to find some compatible hardware. It might take a little while to fix I'm afraid.

**Comment by gpo123** [comment]
Never mind, for me it is working for now with the workaraound described above.

**Comment by terrymacdonald** [comment]
Something like this I really want to make sure I fix for all users, so I've
added it to my bug list to fix for v2.0.0. I think it should work with
HDMI, so I'll make sure it does.

Terry

**Comment by terrymacdonald** [comment]
Hi @gpo123,

I've reviewed your logs, and this is the key one: 

`2021-09-13 13:27:39.5619|WARN|DisplayMagician.ShortcutItem|ShortcutRepository/RefreshValidity: Detected audio playback device PL3461WQ (NVIDIA High Definition Audio) is the one we want, but it is unplugged!`

As you've mentioned, this means that the CoreAudio library talked with Windows, and windows reported that the 'PL3461WQ (NVIDIA High Definition Audio)' device is unplugged. If this device actually was plugged in when it reported it was unplugged, then that points more towards a potential NVIDIA driver issue I'm afraid. The CoreAudio library can only use the information that Windows provides to it.

I've been testing HDMI audio on my test system and DisplayMagician v2.0.0 alpha works perfectly. At the moment I'm using an old AMD HD7790 video card as I've just finished adding AMD Eyefinity support, but its a good test to make sure that the underlying HDMI audio device setting process does work. I'm going to swap over to a later NVIDIA video card this evening, so I'll test HDMI support on the NVIDIA chipsets again just to make sure nothing odd is happening there. 

There's no recent updates to the CoreAudio library for me to update to, and I couldn't see any similar HDMI audio issues in the issues list in the CoreAudio project either. I'll see if it's an NVIDIA driver issue when I do the testing later tonight, as we've had weird NVIDIA introduced problems before (the NVIDIA 2060 Super blank info structure issue springs to mind) but other than that there's not much I can do I'm afraid :(.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oh - one thing I thought of.... do you have another video card you can swap over to for testing? Or is there an onboard video card within your system you can use for testing? Then we can test if your monitor works over HDMI through another video card to eliminate the monitor from the equation....

**Comment by terrymacdonald** [comment]
I'm going to close this for now. Feel free to reopen this if you need to.

Thanks
Terry

**Comment by gpo123** [comment]
Sorry, but I have to open this topic again.
I tried is with release version 2.1.59 and self compiled version 2.2.60.
This time I can provide exact information why this is not working as intended. 
To my setup: I am using 3 Monitors: 2 HD 24" monitor and a 34" 21:9 UW monitor. The latter is only used during gaming, the normal daily work is done on the two HD monitors. During gaming I use the integrated speakers of the 21:9 UW monitor driven by NVIDA digital out. All monitors are wired to the graphics card via Display Port. 
So I setup a display profile consisting of all three monitors with the UW monitor as main monitor. Audio is switched to the UW monitor via this profile. All game shortcuts work with this display profile.
All is working fine as long as this 3 monitor profile is active. Things change when changing from normal to the gaming display. In this situation the UW monitor is on standby and the state of the NVIDIA digital out is "unplugged". Therefore the game shortcut can not be activated with error "Detected capture device PL3461WQ (NVIDIA High Definition Audio) is the one we want, but it is unplugged!"

**Comment by gpo123** [comment]
Exactly. The issue is that the audio is only availabe after the display profile is changed.
My now working workaraound is to test wether the audio is coming from my graphics card and then suppress the error:
ShortcutItem.cs line1329:
if ((audioDevice.State == DeviceState.Unplugged) **&& (audioDevice.FullName.Contains("NVIDIA") == false)**)
Maybe that would work on AMD cards to, but I can´t test as I have no such card available.

**Comment by terrymacdonald** [comment]
Ok, I'll take a look over the next few days. I'll probably get you to test
a test version later this week (or maybe even today if I get some time)

Thanks
Terry

**Comment by terrymacdonald** [comment]
@gpo123 So, I need you to test this test version of DisplayMagician to make sure that the code will work. I've tested it locally, and with some additional changes in the RunShortcut code as well (it now supports unplugged headphones that are plugged in later) this should all work perfectly for you.

Can you please give this a test to make sure that it will work? 

**IMPORTANT: You will need to manually uninstall this test version when the proper DisplayMagician v2.1.0 is released, as it will not automatically upgrade from this test version.**

[DisplayMagicianSetup-v2.1.0.1.zip](https://github.com/terrymacdonald/DisplayMagician/files/7358367/DisplayMagicianSetup-v2.1.0.1.zip)

Thanks
Terry

**Comment by gpo123** [comment]
OK, this is working now. Obviously it should, as you have totally disabled the "unplugged" check ;-)

**Comment by terrymacdonald** [comment]
Excellent! Thanks for your patience on this. And thanks for the donation
too. That was a very nice surprise.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@gpo123 I have recently added code so that DisplayMagician knows the rotation of screens on an AMD card, and shows the rotation properly in the UI. I do not have an AMD card, so I need one of my AMD users to test that it works before I am able to release the updated DisplayMagician version to everyone.

I have created a test version of DisplayMagician and have linked to it below. Can you please download, unzip and install this version to make sure it works? Please report back here in this issue so I know even if it works fine, so I know.

[DisplayMagicianSetup-v2.5.0.337.zip](https://github.com/terrymacdonald/DisplayMagician/files/10312741/DisplayMagicianSetup-v2.5.0.337.zip)

Thanks
Terry
