### ISSUE TITLE
Installation of DisplayMagician v2.0.0-alpha1 fails to register shell extension

### ISSUE THREAD

**Issue by domenic** [terrymacdonald/DisplayMagician#40]
**Describe the bug**
During the installation of the alpha from https://github.com/terrymacdonald/DisplayMagician/issues/23#issuecomment-916453953, I get an error message from the installer that reads

> Module C:\Program Files\DisplayMagician\DisplayMagicianShellExtension.dll failed to register.  HRESULT -214702469.  Contact your support personnel.

Note that I did this after removing DisplayMagician v1 and trying to do a clean install.

**Screenshots**

![image](https://user-images.githubusercontent.com/617481/133171996-8c306ee0-0395-4ea3-86ac-5a7bc5886c35.png)

**Enviroment (please complete the following information):**
 - Windows Version: Win10 21H! (OS Build 19043.1202)
 - DisplayMagician Version 2.0.0-alpha1
 - Date of last windows update: 2021-09-05

**Additional context**

Not sure if this is a big deal; I'm OK without the shell extension for testing. But I thought it'd be worth logging.

**Comment by terrymacdonald** [comment]
Yep, this was a failed attempt to make it easier to upgrade the shell extension by restarting explorer.exe, that failed miserably... I'll back out the change and hopefully that fixes it for the next Alpha.

**Comment by terrymacdonald** [comment]
@domenic Great news. I've got another DisplayMagican v2 build to test. This one has had a lot of local testing, and I've fixed a lot of bugs that I've found. And now I think it's ready for another round of testing. 

I'd really love it if you could test this out for me. To install DisplayMagician v2.0.0-alpha2:

- Firstly, uninstall DisplayMagician v2.0.0 alpha1 if you installed it earlier.
- Secondly, download and install DisplayMagician v2.0.0 alpha2 from this issue
- Thirdly, test it out :).

Hopefully it goes well for you and does everything it should, but if you do find any issues, please log them as new issues here: https://github.com/terrymacdonald/DisplayMagician/issues/new?assignees=terrymacdonald&labels=bug&template=bug_report.md&title=

Thanks 
Terry

[DisplayMagicianSetup-v2.0.0-alpha2.zip](https://github.com/terrymacdonald/DisplayMagician/files/7229458/DisplayMagicianSetup-v2.0.0-alpha2.zip)

**Comment by terrymacdonald** [comment]
Great news! DisplayMagician v2.0.1 has been released, and fixes this very issue. Please test it out, and if you still have any issues please log a new issue.

I'm closing this issue as the fix is in DisplayMagician v2.0.1, and I need to clear out the completed issues so I am able to work on the new issues that come in.

Thanks
Terry
