### ISSUE TITLE
Run programs after game finishes

### ISSUE THREAD

**Issue by gpo123** [terrymacdonald/DisplayMagician#48]
It would be awesome if one could run programs on the "choose what happens afterwards" tab. Just like on the "choose what happens before" tab.
My use case: I am using a VRS DfPro DD wheel. This wheel needs some registry setting to be made to be compatible with older simracing titles (RBR). I would like to be able to revert this settings immediately after the game finishes because otherwise the wheel is not working correctly on the other titles.
Thanks !

**Comment by terrymacdonald** [comment]
@gpo123 Great news. I've added a basic 'run this program afterwards' to the last page of the shortcut editing window to be able to do run one program at the end. This will at least let you either run program or create a powershell/batch file to run more than one thing. Hopefully that is enough for what you need.

Anyway - can you please test, and note any issues you find.  You should be able to install this test version 2.1.0.160 over the top of your last install, but please note you may need to create new profiles, and you **may** need to create new shortcuts as well (please report back if you have to recreate your shortcuts to make it work).

[DisplayMagicianSetup-v2.1.0.160.zip](https://github.com/terrymacdonald/DisplayMagician/files/7480411/DisplayMagicianSetup-v2.1.0.160.zip)

Thanks!
Terry

**Comment by terrymacdonald** [comment]
Hi @gpo123 ,

Can you please test the 'run this program afterwards' functionality for me? While it only provides a single program in this version, it was simple enough to add, so made it into the cut for the new version of DisplayMagician.

We've recently found and fixed an error with the Windows Library and NVIDIA Library that I made. It would come up with an error when it was validating a config, and that would stop the windows portion of the display config being applied. This is now fixed.

Additionally, we had an issue with the NVIDIA Library not correctly applying colour information and failing if a screen with colour information was turned off in a profile. This too has been fixed.

And lastly, the doubled Steam information is fixed. I was accidentally adding the base steam library to the config twice, so all games in the base game library were being scanned twice (doh!). This has been fixed too.

Could you please update your DisplayMagician and test this version? [DisplayMagicianSetup-v2.1.0.215.zip](https://github.com/terrymacdonald/DisplayMagician/files/7531681/DisplayMagicianSetup-v2.1.0.215.zip). I think most of the bugs are now squashed, so I'm sending this copy to my faithful testers to doublecheck the reliability on their own computers before I release this to the general public.

IMPORTANT: I strongly recommend deleting all your existing Display Profiles and recreating them again. This will ensure that your Display Profiles have all the latest fixes applied to them. Once you recreate the Display Profiles you can then go through your shortcuts and update them to use the new profiles.

Thanks
Terry
