### ISSUE TITLE
Display active profile name in notification area icon tooltip

### ISSUE THREAD

**Issue by whitestar127** [terrymacdonald/DisplayMagician#61]
Problem:
To see which profile is active (if it's not self-explanatory due to the way the screens are set up) you have to right-click the icon in the notification area and then move the mouse over the profile option to open the Profiles sub menu. Then you will see the active profile in bold text. Or alternatively you have to open the application window of DisplayMagician and click Display Profiles.

Solution:
Display the active profile name in the tooltip of the icon in the notification area of the Windows taskbar. That way it's fast and simple to see which profile is active.

Alternative:
Display the active profile name as text on the Windows desktop background (not sure if possible).

**Comment by terrymacdonald** [comment]
I will definitely do the tooltip. The profile on the background is a LOT more complicated. I think I'll skip that, or split it into another enhancement and assign it to the future so I don't forget it.

The tooltip will be added to the codebase and then released when 2.1.2 comes out in the next month or two.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@whitestar127 Is this ok? It will be part of DisplayMagician v2.1.2.

![image](https://user-images.githubusercontent.com/5721772/144390613-15da45ea-404b-4ee8-8d8b-6eec8ce725d5.png)

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oh - I've looked at the adding text to the background, and it's just too complicated. It requires that I load the existing background, and then apply text to it and then load the modified background back in. And then I need to have logic that will pick the best text colour for the type of picture, and there is a large chance that I'll ruin the lovely picture people have specially created for their wallpaper. 

So I think I'll just stick with the notification icon :)

If you're happy with the above example picture, then I'll close this issue as the fix will come out with DisplayMagician v2.1.2 as discussed.

Thanks
Terry

**Comment by whitestar127** [comment]
That looks perfect. As long as there's room for a reasonably sized profile name I'm happy.  :-)

**Comment by terrymacdonald** [comment]
Closing issue as it is in the codebase.
