### ISSUE TITLE
W10/Nvidia: Able to apply surround spanning profiles, but unable to apply non-spanning (normal) profiles

### ISSUE THREAD

**Issue by matthewstrasiotto** [terrymacdonald/DisplayMagician#63]
**Describe the bug**
I have a 4 monitor setup in a 2x2 grid (extra, I know) - Presently I have 3 profiles:

- one named "Quad", that configures them as 4 separate displays, and 
- Two that use nvidida's surround spanning:
  - "Surround" : One spans all four monitors into one display
  - "Triforce" : Spans the bottom two monitors, and keeps the top 2 separate

Presently, switching between "Surround" and "Triforce" works as expected, but switching to "Quad" does not.

Switching from: 
- "Quad" -> "Surround" or 
- "Quad" -> "Triforce" 

works normally too.

I can still configure my "Quad" setup via the nvidia control panel manually (Disable surround, positition the monitors)

The behaviour is the same regardless of whether I use a desktop shortcut, or the "Apply" button.

**To Reproduce**
Steps to reproduce the behaviour:

- Apply a spanning profile, or manually configure spanning via NVIDIA control panel
- Choose the "Quad" (non-spanning) profile, and press "Apply"

**Expected behaviour**

The 2x2 non-spanning configuration is applied

**Screenshots**

![image](https://user-images.githubusercontent.com/39424834/144962590-14bf8a45-c0b0-42c5-a4eb-60c52ae0adb1.png)

**Reporting Logs**

[DisplayMagician-Support-20211207-1420.zip](https://github.com/terrymacdonald/DisplayMagician/files/7665270/DisplayMagician-Support-20211207-1420.zip)

**Enviroment (please complete the following information):**
 - Windows Version: W10
 - DisplayMagician Version : 2.1.1
 - Video Card: GeForce GTX 1060 3GB
 - Number and make/model of monitors: 4x Kogan 1080p , 3 DisplayPort, 1 HDMI
 - Driver Version: 456.71
 - Date of last windows update: Idk

**Comment by matthewstrasiotto** [comment]
I've seen similar reports, where a driver update addressed the problem - I'll try that first and update whether that fixes the problem.

**Comment by matthewstrasiotto** [comment]
Upon reflection, I intermittently get a few different odd graphical glitches while playing games (FPS randomly caps at 45, have to swap between fullscreen and borderless to fix, League of Legends minimizes temporarily while clicking around about once a game, etc) so I was probably overdue for a driver update ever since I reinstalled windows.

**Comment by matthewstrasiotto** [comment]
Updating the driver to 497.09 fixes the problem. (Or possibly the system restart that accompanied the update)

**Comment by terrymacdonald** [comment]
Good to hear you found a fix that worked. And very useful for me to know
about this issue, so I can suggest this as a possible fix in the future.

Thanks for logging the issue, and especially for finding the fix yourself
🙂.

Thanks
Terry
