### ISSUE TITLE
Android Tablet SuperDisplay support.

### ISSUE THREAD

**Issue by JSchoonbrood** [terrymacdonald/DisplayMagician#65]
It's difficult to determine whether this is a feature request or a bug.

I have an Android Tablet connected using SuperDisplay, which allows Windows to recognise the tablet as a display, including in display settings. *Shown below*
![image](https://user-images.githubusercontent.com/27826585/145898358-0af0eb39-8ba8-450b-a51e-9336b9e70a8c.png)

However, DisplayMagician does not recognise the tablet as a display. *Shown below*
![image](https://user-images.githubusercontent.com/27826585/145898608-12b5bc03-eb06-4bd6-b8c6-94b0707d7da9.png)

Because it's not recognised as a display, when switching display profiles it turns off the tablet output which isn't ideal. 

---

Ideally, support would be implemented for alternative non-traditional displays. However this may be difficult unless you were to work with SuperDisplay directly or have an android phone or tablet at hand with SuperDisplay drivers installed. 

An alternative solution would be to recognise displays in the current display configuration and compare it to the user's next chosen display configuration and only turn off the displays that were to change state according to the configurations.

Thanks :)

**Comment by terrymacdonald** [comment]
@JSchoonbrood can you please provide a link to the SuperDisplay support site and anywhere that has details about how it works? I'm currently troubleshooting some other issues that may impact this sort of thing, so it would really help if you can sort out some useful links for me to speed p my research later.

Thanks
Terry

**Comment by JSchoonbrood** [comment]
> @JSchoonbrood can you please provide a link to the SuperDisplay support site and anywhere that has details about how it works? I'm currently troubleshooting some other issues that may impact this sort of thing, so it would really help if you can sort out some useful links for me to speed p my research later.
> 
> Thanks Terry

Sure, anything to help.

SuperDisplay Support:
https://superdisplay.app/help/

SuperDisplay Drivers Available Here:
https://superdisplay.app/

SuperDisplay Android App:
https://play.google.com/store/apps/details?id=com.kelocube.mirrorclient

Brief Description on how it works:
"SuperDisplay works just like an external display, so it's the same as if you plugged in a physical display into your computer."

That's about all I can get from the internet, the behind the scenes working I imagine is a little more secretive. However the developer is reachable through:
support@kelocube.com

**Comment by terrymacdonald** [comment]
@JSchoonbrood My gut feel is that for Windows to recognise it, it needs to emulate a PCI or USB connected device. I've just been working to detect USB devices with issue #44 and I think I made a bit of a breakthrough earlier today. The changes I made to my custom WinLibrary code (which handles video card detection and windows display layout) I've included in NVIDIAInfo v1.3.6 available here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.3.6

NVIDIAInfo is my test program that I made to test NVIDIALibrary and WinLibrary, as it allows me to test just the display library components without the rest of DisplayMagician getting in the way.

So, to help me understand a bit more about what's currently happening with SuperDisplay detection, can you please download NVIDIAInfo v1.3.6, and then extract the zip file into a new folder. 

Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Create your superdisplay display layout with some of your screens (superdisplay):
- Save the first windows display as `NVIDIAInfo save superdisplay.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-superdisplay-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal superdisplay.cfg` (we want it to be equal)

Next create a second windows display layout (regular):
- Create a regular display layout with different screens (turn some of the original screens off, and move other ones around, and change the primary monitor)
- Save the second windows display as `NVIDIAInfo save regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)

Next swap back to the superdisplay display layout:
- Load the first windows display as `NVIDIAInfo load superdisplay.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-superdisplay-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal superdisplay.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save superdisplay-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal regular.cfg` (we DO NOT want it to be equal)

Next swap back to the regular display layout:
- Load the second windows display as `NVIDIAInfo load regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save regular-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal superdisplay.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- superdisplay.cfg
- superdisplay-reload.cfg
- NVIDIAInfo-superdisplay-save.log
- NVIDIAInfo-superdisplay-reload.log
- regular.cfg
- regular-reload.cfg
- NVIDIAInfo-regular-save.log
- NVIDIAInfo-regular-reload.log

And then I'll be able to see what's working and what is not, and get a better idea of whether I can do this or not.

Thanks
Terry

**Comment by JSchoonbrood** [comment]
> @JSchoonbrood My gut feel is that for Windows to recognise it, it needs to emulate a PCI or USB connected device. I've just been working to detect USB devices with issue #44 and I think I made a bit of a breakthrough earlier today. The changes I made to my custom WinLibrary code (which handles video card detection and windows display layout) I've included in NVIDIAInfo v1.3.6 available here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.3.6
> 
> NVIDIAInfo is my test program that I made to test NVIDIALibrary and WinLibrary, as it allows me to test just the display library components without the rest of DisplayMagician getting in the way.
> 
> So, to help me understand a bit more about what's currently happening with SuperDisplay detection, can you please download NVIDIAInfo v1.3.6, and then extract the zip file into a new folder.
> 
> Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.
> 
> **IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**
> 
> Please complete the following instructions in this specific order:
> 
> Create your superdisplay display layout with some of your screens (superdisplay):
> 
> * Save the first windows display as `NVIDIAInfo save superdisplay.cfg`
> * Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-superdisplay-save.log"`
> * Check if the first windows display config is equal with `NVIDIAInfo equal superdisplay.cfg` (we want it to be equal)
> 
> Next create a second windows display layout (regular):
> 
> * Create a regular display layout with different screens (turn some of the original screens off, and move other ones around, and change the primary monitor)
> * Save the second windows display as `NVIDIAInfo save regular.cfg`
> * Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-save.log"`
> * Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)
> 
> Next swap back to the superdisplay display layout:
> 
> * Load the first windows display as `NVIDIAInfo load superdisplay.cfg`
> * Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-superdisplay-reload.log"`
> * Check if the first windows display config is equal with `NVIDIAInfo equal superdisplay.cfg` (we want it to be equal)
> * Save a copy of the current display config for me to compare: `NVIDIAInfo save superdisplay-reload.cfg`
> * Make sure the second windows display config is NOT equal with `NVIDIAInfo equal regular.cfg` (we DO NOT want it to be equal)
> 
> Next swap back to the regular display layout:
> 
> * Load the second windows display as `NVIDIAInfo load regular.cfg`
> * Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-reload.log"`
> * Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)
> * Save a copy of the current display config for me to compare: `NVIDIAInfo save regular-reload.cfg`
> * Make sure the first windows display config is NOT equal with `NVIDIAInfo equal superdisplay.cfg` (we DO NOT want it to be equal)
> 
> Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
> 
> * superdisplay.cfg
> * superdisplay-reload.cfg
> * NVIDIAInfo-superdisplay-save.log
> * NVIDIAInfo-superdisplay-reload.log
> * regular.cfg
> * regular-reload.cfg
> * NVIDIAInfo-regular-save.log
> * NVIDIAInfo-regular-reload.log
> 
> And then I'll be able to see what's working and what is not, and get a better idea of whether I can do this or not.
> 
> Thanks Terry

Thank you for the response,
Everyone worked as expected using NVIDIAInfo with display configurations switching perfectly.

Attached are the logs requested :)
[NVIDIA Info Log.zip](https://github.com/terrymacdonald/DisplayMagician/files/7711164/NVIDIA.Info.Log.zip)

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
Ah, the regular.cfg issue may be caused by the fact I turned off the SuperDisplay monitor? I just assumed that as one config was called SuperDisplay.cfg and the other regular.cfg, you may have wanted a display configuration without superdisplay for comparison. 

But apart from that, sounds like good news! Thanks for all your work :)

**Comment by terrymacdonald** [comment]
@JSchoonbrood Can you please download and test NVIDIAInfo v1.3.7 from here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.3.7

IMPORTANT: Please delete the previous CFG and LOG files you created before. I want to test the whole thing again just to be sure it will work.

Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Delete the old CFG and LOG files if you haven't already.

Create your superdisplay display layout with some of your screens (superdisplay):
- Save the first windows display as `NVIDIAInfo save superdisplay.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-superdisplay-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal superdisplay.cfg` (we want it to be equal)

Next create a second windows display layout (regular):
- Create a regular display layout with different screens and without a superdisplay in it (turn some of the original screens off, and move other ones around, and change the primary monitor)
- Save the second windows display as `NVIDIAInfo save regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)

Next swap back to the superdisplay display layout:
- Load the first windows display as `NVIDIAInfo load superdisplay.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-superdisplay-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal superdisplay.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save superdisplay-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal regular.cfg` (we DO NOT want it to be equal)

Next swap back to the regular display layout:
- Load the second windows display as `NVIDIAInfo load regular.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-regular-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal regular.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save regular-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal superdisplay.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- superdisplay.cfg
- superdisplay-reload.cfg
- NVIDIAInfo-superdisplay-save.log
- NVIDIAInfo-superdisplay-reload.log
- regular.cfg
- regular-reload.cfg
- NVIDIAInfo-regular-save.log
- NVIDIAInfo-regular-reload.log

We'll see what effect adding the SuperDisplay PCI detection has done....

Thanks
Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
Thanks for the clarification, all done and all equal tests finished with the expected result. 

[NVIDIAInfo Log 2.zip](https://github.com/terrymacdonald/DisplayMagician/files/7715206/NVIDIAInfo.Log.2.zip)

**Comment by terrymacdonald** [comment]
@JSchoonbrood did you have to load any cfgs twice to get them to apply properly? Or did they work first time?

Thanks
Terry

**Comment by terrymacdonald** [comment]
@JSchoonbrood Oh no! Just checking those log files and I found a mistake in NVIDIAInfo v1.3.7 that prevented the SuperDisplay PCI card matching from working :(. Sorry. 

I've fixed it, and released NVIDIAInfo v1.3.8. Can you please re-run those last tests for me again but using NVIDIAInfo v1.3.8?

https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.3.8

Sorry again :(

Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
The cfgs worked the first time as far as I'm aware.

And no worries, ran all the tests again and finished with the expected results on v1.3.8

Thank you :) 

[NVIDIAInfo Log 3.zip](https://github.com/terrymacdonald/DisplayMagician/files/7718885/NVIDIAInfo.Log.3.zip)

**Comment by terrymacdonald** [comment]
Oh cool! Right, so next step is for me to build this updated library into
DisplayMagician. Then we can test if the GUI works.

I'll put something together during the day, and will post another comment
with it attached. We're so close now...

Thanks
Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
Awesome, thank you!

**Comment by terrymacdonald** [comment]
@JSchoonbrood Can you please install and test this version of DisplayMagician:

[DisplayMagicianSetup-v2.1.1.41.zip](https://github.com/terrymacdonald/DisplayMagician/files/7723505/DisplayMagicianSetup-v2.1.1.41.zip)
 
**If you get any strange behaviour with a DisplayMagician display profile, please delete the Display Profile and create it again. Then update the Game Shortcuts using that Display Profile so that the use the replacement Display Profile** 

Please test the following things:
- Test that you can swap between different Display Profiles (if you have problems please delete the profile and create a new replacement)
- Test that you can create a cloned display profile
- Test that you can create a Surround display profile
- Test that you can create a SuperDisplay profile
- Test that you can swap between all the profiles
- Test that you can use those profiles in some Game Shortcuts, and that the Game Shortcuts work properly.

If you can reply back in this issue with information about if it worked or not that would be great!

Thanks
Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
Awesome,
Done some brief testing.
All profiles and shortcuts are freshly created.

1) Display Magician is able to switch between profiles

2) Display Magician can save a profile that duplicates the display from main monitor to SuperDisplay monitor, however cannot switch to that profile, or switch from that profile properly.

3) Display Magician can use duplicate profiles correctly with other displays (just not SuperDisplays).

4) Display Magician can create a surround profile and switch successfully to and from the profile. The profile does not contain a SuperDisplay as NVIDIA doesn't support that.

5) A standard SuperDisplay extended monitor file can be created and successfully switched to and from, however there is no indication that the profile contains a SuperDisplay (as the graphics are missing) *Shown in screenshot below*
![image](https://user-images.githubusercontent.com/27826585/146285355-ff8e9788-4012-4cb4-86eb-7239eec47ce6.png)

6) Running a game shortcut from a standard display profile to a SuperDisplay profile results in no profile change (aka it doesn't switch profiles)

7) Running a game shortcut from a super display profile to a non SuperDisplay profile results in a successful profile change.

Summary:
SuperDisplay Extended Desktop Switching Works
Game Shortcut switching to SuperDisplay Extended Desktop doesn't work
SuperDisplay Graphics Missing
SuperDisplay Duplicate Screen results in no switching to or from that profile.

Overall: Fairly successful as the main things work!

**Comment by terrymacdonald** [comment]
@JSchoonbrood Can you please do the following steps for me:

- Restart DisplayMagician
- Try applying the Super + Ultra profile
- Go into Settings from the main form and press the 'Create Support ZIP File' button.
- Upload the Support ZIP here so I can review the logs and settings.

Thanks for all your testing so far!
Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
No problem!

Attached is the requested zip file :)
[DisplayMagician-Support-20211216-0106.zip](https://github.com/terrymacdonald/DisplayMagician/files/7723825/DisplayMagician-Support-20211216-0106.zip)

**Comment by terrymacdonald** [comment]
That was fast :) @JSchoonbrood 

OK - I've got a slightly modified logic flow in the bit of code that calculates the screen layout for the GUI, and I also added some extra logging in that area so I'll see a bit more detail. Please do the following again:

- Install DisplayMagician v2.1.1.42 from here: [DisplayMagicianSetup-v2.1.1.42.zip](https://github.com/terrymacdonald/DisplayMagician/files/7723994/DisplayMagicianSetup-v2.1.1.42.zip)
- Open DisplayMagician v2.1.1.42
- Try applying the Super + Ultra profile
- Go into Settings from the main form and press the 'Create Support ZIP File' button.
- Upload the Support ZIP here so I can review the logs and settings.

Thanks! We're getting pretty close I think.
Terry

**Comment by JSchoonbrood** [comment]
Haha yes, saw the email notification just before I was about to call it a night- so thought I'd quickly address it!

Zip file:
[DisplayMagician-Support-20211216-1812.zip](https://github.com/terrymacdonald/DisplayMagician/files/7729561/DisplayMagician-Support-20211216-1812.zip)

Thanks :)

**Comment by terrymacdonald** [comment]
@JSchoonbrood I've just fixed the GUI display for multiple adapters in DisplayMagician v2.1.1.49 test version. I tested it on another computer with multiple adapters and it worked! So please install this new version and test this to make sure that it shows all your displays correctly: 
[DisplayMagicianSetup-v2.1.1.49.zip](https://github.com/terrymacdonald/DisplayMagician/files/7731026/DisplayMagicianSetup-v2.1.1.49.zip)

Thanks
Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 
Can confirm it works as said! Can now see superdisplay in DisplayMagician :) 
Thank you!

**Comment by terrymacdonald** [comment]
@JSchoonbrood Does it work fully? Do the different display profiles get applied correctly as far as you can tell?

Am I able to close this issue now? 

Thanks
Terry

**Comment by terrymacdonald** [comment]
@JSchoonbrood One more thing :)

Can you please test out this new version for me? I've made the windows all resizable. It's a little thing that's been nagging me for a while, so I wanted to get it fixed. Can you please test that the shortcut editing window works, and that the Display Profile window works? There is a possibility that a button or checkbox doesn't work now due to the changes I had to make. Would be great if you could test it for me so I'm sure everything works before the next release.

[DisplayMagicianSetup-v2.1.1.64.zip](https://github.com/terrymacdonald/DisplayMagician/files/7738642/DisplayMagicianSetup-v2.1.1.64.zip)

If everything is fixed, then I'll close this issue, and prepare for a new version of DisplayMagician!

Thanks
Terry

**Comment by JSchoonbrood** [comment]
@terrymacdonald 

Main Window is resizable, expandable and shrinkable, lag-free and all buttons work.

DisplayProfiles window is resizable, expandable and shrinkable but suffers from lag during resizing.

Game shortcuts window is resizable, not expandable but shrinkable and suffers from a little amount of lag compared to DisplayProfiles.

All buttons work on all screens that I could find to test!

**Comment by terrymacdonald** [comment]
Awesome! I think I'm ready to release a new version!

Thank you so much for all your hard work testing. I knew we'd get there in
the end. Sometimes it just takes a while to test each step until I can
isolate the errors.

Thanks again. I'll close this issue now.
Terry

**Comment by terrymacdonald** [comment]
Fixed in codebase. Closing issue.

**Comment by cerahmed** [comment]
Hi there, I stumbled upon this issue as I have the exact same problem.
I have tried the latest stable release as well as downgraded to V2.1.1.64 referenced in this thread in hope that it will solve the issue.

I have an android tablet via Superdisplay as my fifth monitor, and I have created two profiles: 1) with the tablet duplicating my main monitor, and 2) with the tablet as an extended monitor (below screenshot). I cannot apply any of the two profiles .. nothing happens when I click the "Apply" button or change it from the tray icon. Any idea?

![Screenshot 2022-04-17 013145](https://user-images.githubusercontent.com/21166481/163693289-3ec4aab8-0fe2-40d1-b0a0-2556051201dd.png)

**Comment by terrymacdonald** [comment]
Hi,

Can you please create a new issue so that I can track your issue
separately. Please also try installing v2.3.1.12 which is available on
another issue, e.g.
https://github.com/terrymacdonald/DisplayMagician/issues/88

Please see if you still have an issue, and if you do please create a
Support ZIP File from the settings window. Then upload the zip file to that
new issue through your web browser and I'll take a look at the logs.

It could be a problem with Superdisplay, but we should be able to see when
the logs come back.

Thanks
Terry
