### ISSUE TITLE
Fatal Error Windows 11 during creation of game profile

### ISSUE THREAD

**Issue by No-Depth** [terrymacdonald/DisplayMagician#72]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Was attempting to create a game profile when mid creation I got a BSOD and required a restart.  Upon doing so, I had an fatal error pop-up when launching the program again.  This error had an infinite loading loop and I could no longer access the app. 

**Screenshots**

**Reporting Logs**
If DisplayMagician starts:
- Open DisplayMagician and perform whatever actions are needed to make the bug occur.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Come back here, and upload the Support Zip File through your web browser and attach it to this issue.

If DisplayMagician does not:
- Open a terminal window and run `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` to create a TRACE-level DisplayMagician.log file.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- Also attach the following files to this issue:
  - `[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/7787076/DisplayMagician.log) 
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json`
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`

**Enviroment (please complete the following information):**
 - Windows Version: [e.g. Win10]
 - DisplayMagician Version [e.g. 1.1.0]
 - Video Card: [e.g. Asus NVIDIA GTX1070]
 - Number and make/model of 
[DisplayMagician.log](https://github.com/terrymacdonald/DisplayMagician/files/7787068/DisplayMagician.log)
monitors: [e.g. 2xDell UH2718H, 1x LG G27U17D]
 - Date of last video driver update: [e.g. 2021-02-15]
 - Date of last windows update: [e.g. 2021-02-15]

**Additional context**
[DisplayProfiles_2.1.zip](https://github.com/terrymacdonald/DisplayMagician/files/7787081/DisplayProfiles_2.1.zip)

**Comment by terrymacdonald** [comment]
@No-Depth 

Woah! I just checked your Shortcuts_2.0.json file and it's all NUL characters! I've never seen that before. It's the weirdest one yet. Your Display Profiles file looks fine with your two profiles set up. They all look as they should. But your Game Shortcuts was just weird!

To fix your problem I would just delete your Shortcuts_2.0.json file in your C:\Users\brand\AppData\Local\DisplayMagician\Shortcuts folder. This will force DisplayMagician to create a new empty Shortcuts file, and then you can start to add Game Shortcuts to it.

- I've looked through the log file you supplied and I can't find anything weird in there. I did note that the log file seemed to record you saving two display profiles, but didn't seem to have recorded trying to run any game shortcuts. That's fine in this case, as it's really clear that there was a massive error in the Shortcuts_2.0.json file that meant it wouldn't work at all.

My best guess is that DisplayMagician was writing to the Shortcuts json file just as the BSOD happened, and that caused it to fill up with NULs. Deleting the Shortcuts_2.0.json file from your C:\Users\brand\AppData\Local\DisplayMagician\Shortcuts folder will mean that DisplayMagician will start working, and you can recreate your game shortcuts.

As this will fix your problem, I'll close this issue for now. If you find you are still having problems with this after recreating your shortcuts file then please come back here and reopen this issue.

Thanks
Terry
