### ISSUE TITLE
Copy the shortcut commandline to win clipboard

### ISSUE THREAD

**Issue by FormelLMS** [terrymacdonald/DisplayMagician#79]
As I use the Elgato streamdeck it's a bit hard to configure all shortcuts.
I have to save every shortcut to desktop, go to properties and let me show the RunShortcut name. e.g. RunShortcut "2af835b3-adac-4b3e-aad6-de55da35d518"

So I can copy'n'paste this line to my streamdeck for every shortcut. Is there an easy way to copy the shortcuts name to clipboard at rightclicking the shortcut?

For now there are a few things to choose and this one will make it easier (at least for me :) )

**Comment by terrymacdonald** [comment]
@FormeLMS this is a great idea, and fairly simple to implement. I'll add a
'Copy to clipboard' right click menu to each game shortcut and display
profile, and that will copy the full command line that will run
DisplayMagician.

Thanks
Terry

**Comment by FormelLMS** [comment]
Fantastic. Copy command line to clipboard is perfect 👍

**Comment by terrymacdonald** [comment]
@FormelLMS already managed to add **"Send to Clipboard"** to the codebase:

![image](https://user-images.githubusercontent.com/5721772/149724552-f7719616-2521-4933-97f9-76ee99350a39.png)

Will be part of the next release. Generates the following text in Clipboard:

`H:\vscode-projects\DisplayMagician\DisplayMagician\bin\Debug\DisplayMagician.exe RunShortcut "7cc02163-7a8e-4f82-9ba0-9cd5551f08f2"`

Closing this issue as it will be art of the next release.
