### ISSUE TITLE
Keep using the Display Profile after Game ends (permanent change) not working

### ISSUE THREAD

**Issue by stringfieldmark** [terrymacdonald/DisplayMagician#8]
**Describe the bug**
Setting “What happens to the Display Profile afterwards?” to “Keep using the Display Profile after Game ends (permanent change)” on Tab “5. Choose what happens afterwards” doesn’t seem to work.

When closing the game, the profile reverts to the original Display Profile

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup Tabs 1 to 4 as normal
2. Select Tab “5. Choose what happens afterwards”
3. Under “What happens to the Display Profile afterwards?” set the Radio button to “Keep using the Display Profile after Game ends (permanent change)”
4. Save profile
5. Launch Profile

**Expected behaviour**
After closing the launched game, the expectation is for the display to remain on the triple screen setting so another game can be launched easily without the need to revert and redo the triple screen setup.

**Screenshots**
I have added the five tabs with my settings, labelled “Issue2 (tab number)”
![Issue2 (1)](https://user-images.githubusercontent.com/29753726/115236681-90292c00-a113-11eb-8878-a885cf6dc099.png)
![Issue2 (2)](https://user-images.githubusercontent.com/29753726/115236756-a7681980-a113-11eb-8c89-f99171319f51.png)
![Issue2 (3)](https://user-images.githubusercontent.com/29753726/115236763-a931dd00-a113-11eb-8d77-196bf7b2b592.png)
![Issue2 (4)](https://user-images.githubusercontent.com/29753726/115236768-ab943700-a113-11eb-9cba-5f56062f5c88.png)
![Issue2 (5)](https://user-images.githubusercontent.com/29753726/115236780-ae8f2780-a113-11eb-8d5e-aa054efcfc63.png)

**Reporting Logs**
Let me know if required

**Enviroment (please complete the following information):**
 - Windows Version: Windows 10 (20H2 (OS Build 19042.906)
 - DisplayMagician Version: 1.0.4
 - Nvidia GeForce Driver Version: 466.11
 - Graphics card: Asus GTX 1080Ti OC

**Additional context**

**Comment by terrymacdonald** [comment]
I'll take a look over the next few days.

**Comment by terrymacdonald** [comment]
Actually took a look now, and it turned out to be simpler than I thought. Looks like I was missing a check in a single condition. Now testing.

**Comment by terrymacdonald** [comment]
Works on my system. Will be released in v1.1.0.

**Comment by terrymacdonald** [comment]
I also took the liberty of fixing the audio devices and microphones which also didn't retain their settings when the user asked to leave them as is.... oh well. Fixed now. 

Thanks to everyone for their testing.

**Comment by terrymacdonald** [comment]
OK everyone. This *should* be fixed now within v1.0.5 which I've just released. I will close this issue for now, but I will reopen it if there are still problems matching this specific issue.

DisplayMagician should inform you of the new v1.0.5 when you next restart and open it.
