### ISSUE TITLE
Add the possibility to backup the settings 

### ISSUE THREAD

**Issue by FormelLMS** [terrymacdonald/DisplayMagician#80]
I don't know if it's helping many people but for me I love to store, backup and secure my whole settings so if I have a bigger problem I can restore everything.
Is it possible to add a backup thing for display profiles and game shortcuts? At best if it could be scheduled backup in to a chosen place on the system?

**Comment by terrymacdonald** [comment]
Hi @FormelLMS,

I like the idea, but I think this is something a bit far from the core
function of DisplayMagician. I will add some instructions on how to back up
the settings (copy the C:\users\<username>\AppData\Local\DisplayMagician
directory tree) and maybe even add something about using windows backup to
do so.

But I think adding some backup features to DisplayMagician will be a bit
too much.

Thanks for the idea. I never would have thought of this at all.

Thanks
Terry

**Comment by FormelLMS** [comment]
Hey Terry, providing the path is perfectly fine for me. Have my own script for backup and will at that. Is there everything stored? So how the shortcuts are?

**Comment by terrymacdonald** [comment]
yep, they're in the Shortcuts folder, with the data in the Shortcuts_2.0.json file, and the images saved as icon files. It was done this way for easy backup and troubleshooting.

**Comment by FormelLMS** [comment]
Wow. This is real brilliant work. 
I’m satisfied about that.

**Comment by terrymacdonald** [comment]
@FormelLMS, hope this is ok? https://github.com/terrymacdonald/DisplayMagician/wiki/Backing-up-DisplayMagician-settings

I'm going to close this issue now,
