### ISSUE TITLE
Unplugging display and replugging causes domino effect of issues 

### ISSUE THREAD

**Issue by versedi** [terrymacdonald/DisplayMagician#81]
**Describe the bug**
Two plugged monitors will start to be turned on and off, either when you press CMD (Assetto Corsa Content Manager), or even when you dont do anything in certain apps (eg. CCleaner)

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable Surround on 3 displays 1x3 [2 plugged in via DP, one via HDMI] 
2. Unplug one of the monitors plugged [the one plugged in via HDMI port]
3. Plug the above display via DP. 
3. Disable Surround, set it up again with the DP display
4. Enjoy chaos and reinstall of Windows, DDU doesnt fix it. 

**Expected behaviour**
I'm not even sure. I guess you cant prevent people from being dumb like me. Try to fall back to 1 x 1 x 1 from Surround? 

**Screenshots**
[Video should show more](https://youtu.be/-PRUxifIpf8)

**Reporting Logs**
n/a.
My bad. I didn't do it, I tried to remove Display Magician but this issue kept to persist.  My os was basically unusable. 

If DisplayMagician does not:
n/a

**Enviroment (please complete the following information):**
 - Windows Version:  Win10] i think it was the H210 
 - DisplayMagician Version 2.1.15 -> had stucked some install of 1.16 that i updated from to 2.x
 - Video Card:  Gigabyte RTX 2070s
 - Number and make/model of monitors: 3xDell s2721D
 - Date of last video driver update: 2022-01-19 [same version now] 
 - Date of last windows update: 2021-01-21 [Now freshest built after reinstall cause OS was unusable ]

**Additional context**
It might not be Display Magician but I have no other idea what could hook my displays to change resolution when opening apps. I had no other app responsible for such behaviour.

**Comment by terrymacdonald** [comment]
Hmmmm. I'll have to think about this one! DM shouldn't allow this to happen
as it should be detected as another display identifier, and that should
stop it from trying to apply that. I'm not sure why it didn't prevent this
from happening...


I'll have a little think about how I can stop this from occurring, and I'll
double-check the profile matching code again.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@versedi That's really strange behaviour in the video. Is AC Conent Manager set up to do any graphics tweaks? Was there any other display changing software installed at the same time that could have conflicted with DisplayMagician?

DisplayMagician has logic to check for if a profile can be used, and it is set to do that detection when you start to try to apply a display profile, or run a game shortcut. It's really weird that it didn't stop that from happening in your case. The original HDMI Display Profile shouldn't have matched the DP display layout you made, as they will have completely different display identifiers.

Can you please send me a zipped up DisplayMagician config from C:\Users\<username|AppData\Local\DisplayMagician please? I want to see your config files to see what configuration your DisplayMagician had, as it may help me know what DM thought at the time.

Please upload it here (click and drag the zip onto a reply) and I'll take a look.

Thanks
Terry

**Comment by versedi** [comment]
Okay, this is even stranger now.

I'm after Windows reinstall, it worked for single day after format when I just plugged the monitors, restarted the PC configured the surround.

I wasn't using it for couple of days, one of the monitors was unplugged.

Today I've replugged 3rd monitor, restarted PC, turn on Display Magician - everything good in 1 and 2 monitor setup.

The moment I've turned on surround via DM and started Content Manager -> BAM, bug is back.

Unfortunately PC is kinda unusable with it, so this time I'm holding off and uploading the logs you requested.

The title of the issue is completely wrong - it's unrelated to changing the monitor display port. 

This has started to happen since I've updated my Nvidia drivers from October/November one to recent ones - this is the only thing I've changed between having the issue and not having it. The swap of display ports is just a way to reproduce this, apparently either I'm doing something wrong when switching to surround or something wrong happens now. 

00:14 in the logs is the moment I switched to surround and start Content Manager to play. 
00:21 is my switching back to 2 monitors profile which took almost a minute, more than usual. 

[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/7937876/DisplayMagician.zip)

**Comment by versedi** [comment]
Additional comment about Nvidia driver. So, GeForce Experience apparently installs 511.23 GeForce Game Ready Driver, but the website lists the last recommended one as 472.12 released at September 20, 2021. 

Not sure what's with that, I can try downgrading my GGRD drivers to 4xx.xx if you want.

**Comment by versedi** [comment]
```
2022-01-26 00:14:01.5043|TRACE|DisplayMagician.Program|NVIDIALibrary/GetNVIDIADisplayConfig: NvAPI_DISP_GetGDIPrimaryDisplayId returned OK. We have 4 connected displays detected.
```

This is wrong. I have only 3 displays detected in Windows and connected to GPU.

**Comment by versedi** [comment]
I've tried disabling 2x1, disabling DM autostart, restarting PC, setting up the surround manually - the bug persists. 

How is this possible that with DM not even running something controls my application display setup?

**Comment by terrymacdonald** [comment]
Hi Tadeusz,

That NVIDIA Display count is not the same as the Windows connected display
count. The NVIDIA Display count is the number of displays that NVIDIA can
communicate with. It has nothing to do with the Windows 'connected' count.
You should be able to see a count later in the log file from the WinLibrary
which should show the 3 displays connected. The reason for this discrepancy
is that we need to know the actual individual displays and what features
they have so that we know when a particular display profile is valid to be
used.

I would try downgrading your NVIDIA driver version to be honest. It is
possible that it is an NVIDIA driver behaviour change introduced in 511.23,
but it's always hard to know. The NVAPI API we use to control the driver
wasn't updated between 472.12 and 511.23, but that doesn't mean the
underlying functions of the driver itself weren't changed. Uninstalling the
511.23 driver and reinstalling the 472.12 driver could test those changes.

*"I've tried disabling 2x1, disabling DM autostart, restarting PC, setting
> up the surround manually - the bug persists."*


This basically confirms that it is a driver bug. If the NVIDIA driver
itself has this issue, then I would even log it as a ticket at NVIDIA
itself : https://nvidia.custhelp.com  <https://nvidia.custhelp.com>.

There's nothing I can do to fix this I'm afraid :(. It's an upstream NVIDIA
issue.

Thanks

*Terry *

**Comment by versedi** [comment]
Thank you very much for confirming, I'm immediately downgrading to the September driver and will update if the issue persists,

**Comment by versedi** [comment]
For historical log, now working on completely new setup after DDU, just started content manager:

[Completely-Fixed-old-driver-before-braking-DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files
/7938314/Completely-Fixed-old-driver-before-braking-DisplayMagician.zip)

(This comment will be updated with more steps and logs by logs to be able to reproduce the issue to the single most responsible componenet)

**Comment by versedi** [comment]
And now it's same as before my reinstall of whole Windows: 
The Content manager itself works, but Assetto Corsa still does the two monitors to go black when Alt+Tabbing. 
[Still-Broken-After-DDU-old-Driver-DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/7938335/Still-Broken-After-DDU-old-Driver-DisplayMagician.zip)

**Comment by versedi** [comment]
Well I guess I will try restore point from when I installed Windows, completely skip DM, and see if the issue persists, if it does I have no idea what could be stucked so much in some kind of setting .

**Comment by versedi** [comment]
Okay there's more going on then I originally thought. 

I've tried to disable the surround and I was having completely troubles with it - Nvidia Control Panel shown "Conectivity issue" with the displays. 

So I went with Google, unplugged all displays, plugged only the one that was out of surround on HDMI one (it had topology 2x1, 1x1 for some reason). 
Then it allowed me to actually DISABLE the surround, plug the other monitors pack, enable surround and the bug doesn't occur anymore. 

I'm pretty sure if I disable Surround, unplug one of monitors (or just disable it on power button), restart PC, plug monitor in or enable it, restart PC - I should be able to reproduce it now completely.

**Comment by versedi** [comment]
Unrelated to Display Magician - either bug with Gsync and my combination of displays or something else that I'm yet to understand.

Same settings work and don't work at the same time - it's a roulette if it will happen or not.

If anyone stumbles uppon this issue from Google: disable gsync, apply. enable gsync apply. If it doesn't work repeat until it works. Also check the "override the scaling mode set by games and programs" in adjust desktop size and position inside Nvidia Control Panel - not sure if it helped but it seems like I get more consistent result with it's checked. It's still a roulette though.

**Comment by terrymacdonald** [comment]
Good luck Tadeusz,

Hopefully it's a bug in 511.23. It looks like this last release of NVIDIA
was a big one, so it's entirely possible that there are some new bugs in
there.

Thanks

*Terry *

**Comment by versedi** [comment]
Edited title so people with similar trouble have easier way to find it.
