### ISSUE TITLE
Second "Wait until an alternative executable is closed before continuing" option

### ISSUE THREAD

**Issue by stringfieldmark** [terrymacdonald/DisplayMagician#9]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem but I have found that if I want the triple screen setup to remain, and only revert to a single monitor setup after I have closed a **specific** program and not the game, on Tab 4 I need to select the "Launch a Game executable" option and place the executable in the "Wait until an alternative executable is closed before continuing" option. When using the "Launch a Game installed in Steam or Uplay" option, I only then have the option of either leaving the triple screen running or reverting to a single screen when closing the game, as set on Tab 5.

**Describe the solution you'd like**
It would be great to have the same option as under the "Launch a Game executable" labelled "Wait until an alternative executable is closed before continuing" option under the "Launch a Game installed in Steam or Uplay" option

**Describe alternatives you've considered**
On Tab 4 I select the "Launch a Game executable" option and place the executable in the "Wait until an alternative executable is closed before continuing" option. This makes the ease of using the "Launch a Game installed in Steam or Uplay" option redundant for me even though all the games are nicely listed.

**Additional context**
I have a mock-up of what it may look like below:

Add another option to below the Steam and Uplay section
<img width="556" alt="Feature Request 1" src="https://user-images.githubusercontent.com/29753726/115240286-7db0f180-a117-11eb-87f6-c358b279fa5e.png">

Or

Move the existing one to the bottom and have the code duplicate for either scenario
<img width="556" alt="Feature Request 1" src="https://user-images.githubusercontent.com/29753726/115243367-c4541b00-a11a-11eb-8dc7-7069f8b06113.png">

**Comment by terrymacdonald** [comment]
Hmmmmm. Interesting idea. Not one I even thought about before you've suggested it. 

I've just rewritten the detection logic to be a bit more scalable, and this feature could work with the new code. I'll have a bit more of a think about it, and see what I can do.

**Comment by terrymacdonald** [comment]
ok - FYI I am partway through the addition of this feature. It requires quite a bit of update to UI and internal data model which has been a tad painful. I still have to complete file selection dialog and the actual code that does the monitoring....

**Comment by terrymacdonald** [comment]
OK @stringfieldmark. This is in v1.0.5 which I've just released. 

DisplayMagician should inform you of the new v1.0.5 when you next restart and open it.
