### ISSUE TITLE
Ability to disable "DisplayMagician Minimized" notification

### ISSUE THREAD

**Issue by RBZL** [terrymacdonald/DisplayMagician#99]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The notification that DisplayMagician is minimized and will wait in the background until you need it is a bit of a nuisance. I would like to be able to disable that notification.

**Describe alternatives you've considered**
If this is the only notification DisplayMagician pushes, I could turn off notifications for DisplayMagician via Windows settings for the app entirely. However, if there are other notifications I may want to know about, I don't want to do that.

**Additional context**
N/A

**Comment by terrymacdonald** [comment]
I'll look at what I can do in this space. I'm conscious of making the setting screen too complicated, so I'll have a think what I can do here.

Terry

**Comment by terrymacdonald** [comment]
I think I have a working solution:

![image](https://user-images.githubusercontent.com/5721772/166662691-df4cbd06-c50a-403b-ae1c-c4408999eba1.png)

That will let a user choose to only remove the minimise Action Center message, or to turn off all the Action Center messages to be completely silent.

As I have now added the code to the DisplayMagician main codebase I will close this issue. The code will be released in the next release of DisplayMagician v2.4.0
